// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenLogo_screen_init();
    ui_ScreenMain_screen_init();
    ui_ScreenDate_screen_init();
    ui_ScreenSettings_screen_init();
    ui_ScreenTimer_screen_init();
    ui_ScreenOption_screen_init();
    ui_ScreenPin_screen_init();
    ui_ScreenAdvanced_screen_init();
    ui_ScreenModes_screen_init();
    ui_ScreenControl_screen_init();
    ui_ScreenInfo_screen_init();
    ui_ScreenInfoSetup_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenLogo);
}

void ui_destroy(void)
{
    ui_ScreenLogo_screen_destroy();
    ui_ScreenMain_screen_destroy();
    ui_ScreenDate_screen_destroy();
    ui_ScreenSettings_screen_destroy();
    ui_ScreenTimer_screen_destroy();
    ui_ScreenOption_screen_destroy();
    ui_ScreenPin_screen_destroy();
    ui_ScreenAdvanced_screen_destroy();
    ui_ScreenModes_screen_destroy();
    ui_ScreenControl_screen_destroy();
    ui_ScreenInfo_screen_destroy();
    ui_ScreenInfoSetup_screen_destroy();
}
