// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef _HMI_ESP32_S3_7B_UI_H
#define _HMI_ESP32_S3_7B_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenLogo.h"
#include "screens/ui_ScreenMain.h"
#include "screens/ui_ScreenDate.h"
#include "screens/ui_ScreenSettings.h"
#include "screens/ui_ScreenTimer.h"
#include "screens/ui_ScreenOption.h"
#include "screens/ui_ScreenPin.h"
#include "screens/ui_ScreenAdvanced.h"
#include "screens/ui_ScreenModes.h"
#include "screens/ui_ScreenControl.h"
#include "screens/ui_ScreenInfo.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1615156922);    // assets/ES-BEJE-BRANCO.png
LV_IMG_DECLARE(ui_img_phone1_png);    // assets/Phone1.png
LV_IMG_DECLARE(ui_img_work_png);    // assets/work.png
LV_IMG_DECLARE(ui_img_relax_png);    // assets/relax.png
LV_IMG_DECLARE(ui_img_fan_png);    // assets/fan.png
LV_IMG_DECLARE(ui_img_led_png);    // assets/led.png
LV_IMG_DECLARE(ui_img_private_png);    // assets/Private.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_clean_png);    // assets/clean.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_timer_fan_png);    // assets/timer_fan.png
LV_IMG_DECLARE(ui_img_timer_led_png);    // assets/timer_led.png
LV_IMG_DECLARE(ui_img_timer_png);    // assets/timer.png
LV_IMG_DECLARE(ui_img_data_png);    // assets/data.png
LV_IMG_DECLARE(ui_img_control_png);    // assets/control.png
LV_IMG_DECLARE(ui_img_pin_png);    // assets/pin.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_info_png);    // assets/info.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
