// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_ButtonPhone_Clicked(lv_event_t * e);
void ui_event_ButtonWork_Clicked(lv_event_t * e);
void ui_event_ButtonRelax_Clicked(lv_event_t * e);
void ui_event_FanSlider_ValueChanged(lv_event_t * e);
void ui_event_LightSlider_ValueChanged(lv_event_t * e);
void ui_event_PrivateSlider_ValueChanged(lv_event_t * e);
void ui_event_ButtonSettings_Clicked(lv_event_t * e);
void ui_event_ButtonClean_Clicked(lv_event_t * e);
void ui_event_ButtonSaveDate_Clicked(lv_event_t * e);
void ui_event_ButtonBackDate_Clicked(lv_event_t * e);
void ui_event_RollerAno_ValueChanged(lv_event_t * e);
void ui_event_RollerMes_ValueChanged(lv_event_t * e);
void ui_event_RollerDia_ValueChanged(lv_event_t * e);
void ui_event_RollerH_ValueChanged(lv_event_t * e);
void ui_event_RollerM_ValueChanged(lv_event_t * e);
void ui_event_DropdownFormat_ValueChanged(lv_event_t * e);
void ui_event_DropdownAmPm_ValueChanged(lv_event_t * e);
void ui_event_TextAreaPinSettings_Focused(lv_event_t * e);
void ui_event_TextAreaPinSettings_Defocused(lv_event_t * e);
void ui_event_Button1_Clicked(lv_event_t * e);
void ui_event_Button2_Clicked(lv_event_t * e);
void ui_event_Button3_Clicked(lv_event_t * e);
void ui_event_Button4_Clicked(lv_event_t * e);
void ui_event_Button5_Clicked(lv_event_t * e);
void ui_event_Button6_Clicked(lv_event_t * e);
void ui_event_Button7_Clicked(lv_event_t * e);
void ui_event_Button8_Clicked(lv_event_t * e);
void ui_event_Button9_Clicked(lv_event_t * e);
void ui_event_ButtonDel_Clicked(lv_event_t * e);
void ui_event_Button0_Clicked(lv_event_t * e);
void ui_event_ButtonOk_Clicked(lv_event_t * e);
void ui_event_ButtonBackHome_Clicked(lv_event_t * e);
void ui_event_ButtonSaveTimer_clicked(lv_event_t * e);
void ui_event_RollerFanTimer_Ready(lv_event_t * e);
void ui_event_RollerFanTimer_Change(lv_event_t * e);
void ui_event_RollerLedTimer_Ready(lv_event_t * e);
void ui_event_RollerLedTimer_Change(lv_event_t * e);
void ui_event_ButtonBackTimer_Clicked(lv_event_t * e);
void ui_event_ButtonTimer_Clicked(lv_event_t * e);
void ui_event_ButtonDate_Clicked(lv_event_t * e);
void ui_event_ButtonModes_Clicked(lv_event_t * e);
void ui_event_ButtonBackOption_Clicked(lv_event_t * e);
void ui_event_PinUser_Focused(lv_event_t * e);
void ui_event_PinUser_Defocused(lv_event_t * e);
void ui_event_PinAdvanced_Focused(lv_event_t * e);
void ui_event_PinAdvanced_Defocused(lv_event_t * e);
void ui_event_ButtonBackPin_Clicked(lv_event_t * e);
void ui_event_ButtonPin_Clicked(lv_event_t * e);
void ui_event_ButtonInfo_Clicked(lv_event_t * e);
void ui_event_ButtonBackAdvanced_Clicked(lv_event_t * e);
void ui_event_RollerModes_Ready(lv_event_t * e);
void ui_event_RollerModes_Change(lv_event_t * e);
void ui_event_ModesFanSlider_ValueChanged(lv_event_t * e);
void ui_event_ModesLightSlider_ValueChanged(lv_event_t * e);
void ui_event_ModesPrivateSlider_ValueChanged(lv_event_t * e);
void ui_event_ButtonBackModes_Clicked(lv_event_t * e);
void ui_event_ButtonSaveModes_Clicked(lv_event_t * e);
void ui_event_ButtonBackControl_Clicked(lv_event_t * e);
void ui_event_IR_Enable(lv_event_t * e);
void ui_event_ButtonBackInfo_Clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
