// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef _UI_COMP_PANELNUMBER_H
#define _UI_COMP_PANELNUMBER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PanelNumber
#define UI_COMP_PANELNUMBER_PANELNUMBER 0
#define UI_COMP_PANELNUMBER_BUTTON1 1
#define UI_COMP_PANELNUMBER_BUTTON1_LABEL1 2
#define UI_COMP_PANELNUMBER_BUTTON2 3
#define UI_COMP_PANELNUMBER_BUTTON2_LABEL2 4
#define UI_COMP_PANELNUMBER_BUTTON3 5
#define UI_COMP_PANELNUMBER_BUTTON3_LABEL3 6
#define UI_COMP_PANELNUMBER_BUTTON4 7
#define UI_COMP_PANELNUMBER_BUTTON4_LABEL4 8
#define UI_COMP_PANELNUMBER_BUTTON5 9
#define UI_COMP_PANELNUMBER_BUTTON5_LABEL5 10
#define UI_COMP_PANELNUMBER_BUTTON6 11
#define UI_COMP_PANELNUMBER_BUTTON6_LABEL6 12
#define UI_COMP_PANELNUMBER_BUTTON7 13
#define UI_COMP_PANELNUMBER_BUTTON7_LABEL7 14
#define UI_COMP_PANELNUMBER_BUTTON8 15
#define UI_COMP_PANELNUMBER_BUTTON8_LABEL8 16
#define UI_COMP_PANELNUMBER_BUTTON9 17
#define UI_COMP_PANELNUMBER_BUTTON9_LABEL9 18
#define UI_COMP_PANELNUMBER_BUTTONDEL 19
#define UI_COMP_PANELNUMBER_BUTTONDEL_LABELDEL 20
#define UI_COMP_PANELNUMBER_BUTTON0 21
#define UI_COMP_PANELNUMBER_BUTTON0_LABEL0 22
#define UI_COMP_PANELNUMBER_BUTTONOK 23
#define UI_COMP_PANELNUMBER_BUTTONOK_LABELOK 24
#define _UI_COMP_PANELNUMBER_NUM 25
lv_obj_t * ui_PanelNumber_create(lv_obj_t * comp_parent);
void ui_event_comp_PanelNumber_Button1(lv_event_t * e);
void ui_event_comp_PanelNumber_Button2(lv_event_t * e);
void ui_event_comp_PanelNumber_Button3(lv_event_t * e);
void ui_event_comp_PanelNumber_Button4(lv_event_t * e);
void ui_event_comp_PanelNumber_Button5(lv_event_t * e);
void ui_event_comp_PanelNumber_Button6(lv_event_t * e);
void ui_event_comp_PanelNumber_Button7(lv_event_t * e);
void ui_event_comp_PanelNumber_Button8(lv_event_t * e);
void ui_event_comp_PanelNumber_Button9(lv_event_t * e);
void ui_event_comp_PanelNumber_ButtonDel(lv_event_t * e);
void ui_event_comp_PanelNumber_Button0(lv_event_t * e);
void ui_event_comp_PanelNumber_ButtonOk(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
