// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

void ui_event_comp_Slider1_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_Slider1 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(comp_Slider1[UI_COMP_SLIDER1_LABEL1], target, "", "");
    }
}

// COMPONENT Slider1

lv_obj_t * ui_Slider1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Slider1;
    cui_Slider1 = lv_slider_create(comp_parent);
    lv_slider_set_value(cui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider1, 120);
    lv_obj_set_height(cui_Slider1, 240);
    lv_obj_set_align(cui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_Slider1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider1, lv_color_hex(0x003446), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Slider1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider1, lv_color_hex(0xFBFAFA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(cui_Slider1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Slider1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(cui_Slider1, lv_color_hex(0x4B4B52), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(cui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(cui_Slider1, true, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(cui_Slider1, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Slider1, 10, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_color(cui_Slider1, lv_color_hex(0xE51B1B), LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(cui_Slider1, 255, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_grad_dir(cui_Slider1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_clip_corner(cui_Slider1, false, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_color(cui_Slider1, lv_color_hex(0x000000),
                                  LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(cui_Slider1, 255, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_side(cui_Slider1, LV_BORDER_SIDE_FULL, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_color(cui_Slider1, lv_color_hex(0x000000),
                                   LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(cui_Slider1, 255, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(cui_Slider1, 0, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_blend_mode(cui_Slider1, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_Slider1);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label1, 0);
    lv_obj_set_y(cui_Label1, -75);
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "50");
    lv_label_set_recolor(cui_Label1, "true");
    lv_obj_set_style_text_color(cui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SLIDER1_NUM);
    children[UI_COMP_SLIDER1_SLIDER1] = cui_Slider1;
    children[UI_COMP_SLIDER1_LABEL1] = cui_Label1;
    lv_obj_add_event_cb(cui_Slider1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Slider1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Slider1, ui_event_comp_Slider1_Slider1, LV_EVENT_ALL, children);
    ui_comp_Slider1_create_hook(cui_Slider1);
    return cui_Slider1;
}

