// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef _UI_COMP_SLIDER1_H
#define _UI_COMP_SLIDER1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Slider1
#define UI_COMP_SLIDER1_SLIDER1 0
#define UI_COMP_SLIDER1_LABEL1 1
#define _UI_COMP_SLIDER1_NUM 2
lv_obj_t * ui_Slider1_create(lv_obj_t * comp_parent);
void ui_event_comp_Slider1_Slider1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
