// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

// COMPONENT topBar

lv_obj_t * ui_topBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_topBar;
    cui_topBar = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_topBar);
    lv_obj_set_width(cui_topBar, 1024);
    lv_obj_set_height(cui_topBar, 70);
    lv_obj_set_align(cui_topBar, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(cui_topBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(cui_topBar, LV_SCROLLBAR_MODE_OFF);

    lv_obj_t * cui_LabelMenu;
    cui_LabelMenu = lv_label_create(cui_topBar);
    lv_obj_set_width(cui_LabelMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LabelMenu, 0);
    lv_obj_set_y(cui_LabelMenu, 10);
    lv_obj_set_align(cui_LabelMenu, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelMenu, "Home");
    lv_obj_set_style_text_font(cui_LabelMenu, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_IndicatorCabin;
    cui_IndicatorCabin = lv_obj_create(cui_topBar);
    lv_obj_set_width(cui_IndicatorCabin, 350);
    lv_obj_set_height(cui_IndicatorCabin, 30);
    lv_obj_set_x(cui_IndicatorCabin, 0);
    lv_obj_set_y(cui_IndicatorCabin, -27);
    lv_obj_set_align(cui_IndicatorCabin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_IndicatorCabin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_IndicatorCabin, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_IndicatorCabin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(cui_IndicatorCabin, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelDateTime;
    cui_LabelDateTime = lv_label_create(cui_topBar);
    lv_obj_set_width(cui_LabelDateTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelDateTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LabelDateTime, -50);
    lv_obj_set_y(cui_LabelDateTime, 15);
    lv_obj_set_align(cui_LabelDateTime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_LabelDateTime, "--/--/---- --:--\n");
    lv_obj_set_style_text_font(cui_LabelDateTime, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TOPBAR_NUM);
    children[UI_COMP_TOPBAR_TOPBAR] = cui_topBar;
    children[UI_COMP_TOPBAR_LABELMENU] = cui_LabelMenu;
    children[UI_COMP_TOPBAR_INDICATORCABIN] = cui_IndicatorCabin;
    children[UI_COMP_TOPBAR_LABELDATETIME] = cui_LabelDateTime;
    lv_obj_add_event_cb(cui_topBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_topBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_topBar_create_hook(cui_topBar);
    return cui_topBar;
}

