// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

void ui_comp_Container1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Slider1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_topBar_create_hook(lv_obj_t * comp)
{
}

void ui_comp_bottomBar_create_hook(lv_obj_t * comp)
{
}

void ui_comp_BottomBar_create_hook(lv_obj_t * comp)
{
}

void ui_comp_PanelNumber_create_hook(lv_obj_t * comp)
{
}
