// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

void ui_event_comp_PanelNumber_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button1_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button2_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button3_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button4_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button5_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button6_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button7_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button8_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button9_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_ButtonDel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonDel_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_Button0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_Button0_Clicked(e);
    }
}

void ui_event_comp_PanelNumber_ButtonOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_PanelNumber = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonOk_Clicked(e);
    }
}

// COMPONENT PanelNumber

lv_obj_t * ui_PanelNumber_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_PanelNumber;
    cui_PanelNumber = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_PanelNumber, 556);
    lv_obj_set_height(cui_PanelNumber, 390);
    lv_obj_set_x(cui_PanelNumber, 0);
    lv_obj_set_y(cui_PanelNumber, 80);
    lv_obj_set_align(cui_PanelNumber, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PanelNumber, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_PanelNumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_PanelNumber, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_PanelNumber, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_PanelNumber, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_PanelNumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_PanelNumber, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button1;
    cui_Button1 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button1, 170);
    lv_obj_set_height(cui_Button1, 90);
    lv_obj_set_x(cui_Button1, -10);
    lv_obj_set_y(cui_Button1, -15);
    lv_obj_add_flag(cui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_Button1);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "1");
    lv_label_set_recolor(cui_Label1, "true");
    lv_obj_set_style_text_font(cui_Label1, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button2;
    cui_Button2 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button2, 170);
    lv_obj_set_height(cui_Button2, 90);
    lv_obj_set_x(cui_Button2, 0);
    lv_obj_set_y(cui_Button2, -15);
    lv_obj_set_align(cui_Button2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label2;
    cui_Label2 = lv_label_create(cui_Button2);
    lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label2, "2");
    lv_label_set_recolor(cui_Label2, "true");
    lv_obj_set_style_text_font(cui_Label2, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button3;
    cui_Button3 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button3, 170);
    lv_obj_set_height(cui_Button3, 90);
    lv_obj_set_x(cui_Button3, 10);
    lv_obj_set_y(cui_Button3, -15);
    lv_obj_set_align(cui_Button3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(cui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button3, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(cui_Button3);
    lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label3, "3");
    lv_label_set_recolor(cui_Label3, "true");
    lv_obj_set_style_text_font(cui_Label3, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_t * cui_Button4;
    cui_Button4 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button4, 170);
    lv_obj_set_height(cui_Button4, 90);
    lv_obj_set_x(cui_Button4, -10);
    lv_obj_set_y(cui_Button4, -50);
    lv_obj_set_align(cui_Button4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(cui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button4, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_Button4);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "4");
    lv_label_set_recolor(cui_Label4, "true");
    lv_obj_set_style_text_font(cui_Label4, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_t * cui_Button5;
    cui_Button5 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button5, 170);
    lv_obj_set_height(cui_Button5, 90);
    lv_obj_set_x(cui_Button5, 0);
    lv_obj_set_y(cui_Button5, -50);
    lv_obj_set_align(cui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button5, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label5;
    cui_Label5 = lv_label_create(cui_Button5);
    lv_obj_set_width(cui_Label5, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label5, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label5, "5");
    lv_label_set_recolor(cui_Label5, "true");
    lv_obj_set_style_text_font(cui_Label5, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button6;
    cui_Button6 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button6, 170);
    lv_obj_set_height(cui_Button6, 90);
    lv_obj_set_x(cui_Button6, 10);
    lv_obj_set_y(cui_Button6, -50);
    lv_obj_set_align(cui_Button6, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button6, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label6;
    cui_Label6 = lv_label_create(cui_Button6);
    lv_obj_set_width(cui_Label6, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label6, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label6, "6");
    lv_label_set_recolor(cui_Label6, "true");
    lv_obj_set_style_text_font(cui_Label6, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button7;
    cui_Button7 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button7, 170);
    lv_obj_set_height(cui_Button7, 90);
    lv_obj_set_x(cui_Button7, -10);
    lv_obj_set_y(cui_Button7, -85);
    lv_obj_set_align(cui_Button7, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(cui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button7, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label7;
    cui_Label7 = lv_label_create(cui_Button7);
    lv_obj_set_width(cui_Label7, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label7, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label7, "7");
    lv_label_set_recolor(cui_Label7, "true");
    lv_obj_set_style_text_font(cui_Label7, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button8;
    cui_Button8 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button8, 170);
    lv_obj_set_height(cui_Button8, 90);
    lv_obj_set_x(cui_Button8, 0);
    lv_obj_set_y(cui_Button8, -85);
    lv_obj_set_align(cui_Button8, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(cui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button8, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button8, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button8, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label8;
    cui_Label8 = lv_label_create(cui_Button8);
    lv_obj_set_width(cui_Label8, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label8, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label8, "8");
    lv_label_set_recolor(cui_Label8, "true");
    lv_obj_set_style_text_font(cui_Label8, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button9;
    cui_Button9 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button9, 170);
    lv_obj_set_height(cui_Button9, 90);
    lv_obj_set_x(cui_Button9, 10);
    lv_obj_set_y(cui_Button9, -85);
    lv_obj_set_align(cui_Button9, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(cui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button9, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button9, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label9;
    cui_Label9 = lv_label_create(cui_Button9);
    lv_obj_set_width(cui_Label9, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label9, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label9, "9");
    lv_label_set_recolor(cui_Label9, "true");
    lv_obj_set_style_text_font(cui_Label9, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ButtonDel;
    cui_ButtonDel = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_ButtonDel, 170);
    lv_obj_set_height(cui_ButtonDel, 90);
    lv_obj_set_x(cui_ButtonDel, -10);
    lv_obj_set_y(cui_ButtonDel, 10);
    lv_obj_set_align(cui_ButtonDel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(cui_ButtonDel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonDel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ButtonDel, lv_color_hex(0xE74C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonDel, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ButtonDel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ButtonDel, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ButtonDel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_ButtonDel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelDel;
    cui_LabelDel = lv_label_create(cui_ButtonDel);
    lv_obj_set_width(cui_LabelDel, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_LabelDel, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_LabelDel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelDel, "DEL");
    lv_label_set_recolor(cui_LabelDel, "true");
    lv_obj_set_style_text_font(cui_LabelDel, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button0;
    cui_Button0 = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_Button0, 170);
    lv_obj_set_height(cui_Button0, 90);
    lv_obj_set_x(cui_Button0, 0);
    lv_obj_set_y(cui_Button0, 10);
    lv_obj_set_align(cui_Button0, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(cui_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button0, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Button0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Button0, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Button0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_Button0, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label0;
    cui_Label0 = lv_label_create(cui_Button0);
    lv_obj_set_width(cui_Label0, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Label0, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_Label0, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label0, "0");
    lv_label_set_recolor(cui_Label0, "true");
    lv_obj_set_style_text_font(cui_Label0, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);
 
    lv_obj_t * cui_ButtonOk;
    cui_ButtonOk = lv_btn_create(cui_PanelNumber);
    lv_obj_set_width(cui_ButtonOk, 170);
    lv_obj_set_height(cui_ButtonOk, 90);
    lv_obj_set_x(cui_ButtonOk, 10);
    lv_obj_set_y(cui_ButtonOk, 10);
    lv_obj_set_align(cui_ButtonOk, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(cui_ButtonOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ButtonOk, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonOk, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ButtonOk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ButtonOk, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ButtonOk, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_ButtonOk, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelOk;
    cui_LabelOk = lv_label_create(cui_ButtonOk);
    lv_obj_set_width(cui_LabelOk, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_LabelOk, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(cui_LabelOk, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelOk, "OK");
    lv_label_set_recolor(cui_LabelOk, "true");
    lv_obj_set_style_text_font(cui_LabelOk, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANELNUMBER_NUM);
    children[UI_COMP_PANELNUMBER_PANELNUMBER] = cui_PanelNumber;
    children[UI_COMP_PANELNUMBER_BUTTON1] = cui_Button1;
    children[UI_COMP_PANELNUMBER_BUTTON1_LABEL1] = cui_Label1;
    children[UI_COMP_PANELNUMBER_BUTTON2] = cui_Button2;
    children[UI_COMP_PANELNUMBER_BUTTON2_LABEL2] = cui_Label2;
    children[UI_COMP_PANELNUMBER_BUTTON3] = cui_Button3;
    children[UI_COMP_PANELNUMBER_BUTTON3_LABEL3] = cui_Label3;
    children[UI_COMP_PANELNUMBER_BUTTON4] = cui_Button4;
    children[UI_COMP_PANELNUMBER_BUTTON4_LABEL4] = cui_Label4;
    children[UI_COMP_PANELNUMBER_BUTTON5] = cui_Button5;
    children[UI_COMP_PANELNUMBER_BUTTON5_LABEL5] = cui_Label5;
    children[UI_COMP_PANELNUMBER_BUTTON6] = cui_Button6;
    children[UI_COMP_PANELNUMBER_BUTTON6_LABEL6] = cui_Label6;
    children[UI_COMP_PANELNUMBER_BUTTON7] = cui_Button7;
    children[UI_COMP_PANELNUMBER_BUTTON7_LABEL7] = cui_Label7;
    children[UI_COMP_PANELNUMBER_BUTTON8] = cui_Button8;
    children[UI_COMP_PANELNUMBER_BUTTON8_LABEL8] = cui_Label8;
    children[UI_COMP_PANELNUMBER_BUTTON9] = cui_Button9;
    children[UI_COMP_PANELNUMBER_BUTTON9_LABEL9] = cui_Label9;
    children[UI_COMP_PANELNUMBER_BUTTONDEL] = cui_ButtonDel;
    children[UI_COMP_PANELNUMBER_BUTTONDEL_LABELDEL] = cui_LabelDel;
    children[UI_COMP_PANELNUMBER_BUTTON0] = cui_Button0;
    children[UI_COMP_PANELNUMBER_BUTTON0_LABEL0] = cui_Label0;
    children[UI_COMP_PANELNUMBER_BUTTONOK] = cui_ButtonOk;
    children[UI_COMP_PANELNUMBER_BUTTONOK_LABELOK] = cui_LabelOk;
    lv_obj_add_event_cb(cui_PanelNumber, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_PanelNumber, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button1, ui_event_comp_PanelNumber_Button1, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button2, ui_event_comp_PanelNumber_Button2, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button3, ui_event_comp_PanelNumber_Button3, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button4, ui_event_comp_PanelNumber_Button4, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button5, ui_event_comp_PanelNumber_Button5, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button6, ui_event_comp_PanelNumber_Button6, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button7, ui_event_comp_PanelNumber_Button7, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button8, ui_event_comp_PanelNumber_Button8, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button9, ui_event_comp_PanelNumber_Button9, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_ButtonDel, ui_event_comp_PanelNumber_ButtonDel, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Button0, ui_event_comp_PanelNumber_Button0, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_ButtonOk, ui_event_comp_PanelNumber_ButtonOk, LV_EVENT_ALL, children);
    ui_comp_PanelNumber_create_hook(cui_PanelNumber);
    return cui_PanelNumber;
}

