// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef _HMI_ESP32_S3_7B_UI_COMP_HOOK_H
#define _HMI_ESP32_S3_7B_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_PanelNumber_create_hook(lv_obj_t * comp);
void ui_comp_Slider1_create_hook(lv_obj_t * comp);
void ui_comp_topBar_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
