// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENOPTION_H
#define UI_SCREENOPTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenOption
extern void ui_ScreenOption_screen_init(void);
extern void ui_ScreenOption_screen_destroy(void);
extern lv_obj_t * ui_ScreenOption;
extern lv_obj_t * ui_ContainerOption;
extern lv_obj_t * ui_topBar1;
extern lv_obj_t * ui_PanelTimer;
extern lv_obj_t * ui_LabelTimer;
extern void ui_event_ButtonTimer(lv_event_t * e);
extern lv_obj_t * ui_ButtonTimer;
extern lv_obj_t * ui_PanelDate;
extern lv_obj_t * ui_LabelDate;
extern void ui_event_ButtonDate(lv_event_t * e);
extern lv_obj_t * ui_ButtonDate;
extern lv_obj_t * ui_PanelModes;
extern lv_obj_t * ui_LabelModes;
extern void ui_event_ButtonModes(lv_event_t * e);
extern lv_obj_t * ui_ButtonModes;
extern lv_obj_t * ui_PanelBackOption;
extern void ui_event_ButtonBackOption(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackOption;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenOption;
extern lv_obj_t * uic_ContainerOption;
extern lv_obj_t * uic_PanelTimer;
extern lv_obj_t * uic_LabelTimer;
extern lv_obj_t * uic_ButtonTimer;
extern lv_obj_t * uic_PanelDate;
extern lv_obj_t * uic_LabelDate;
extern lv_obj_t * uic_ButtonDate;
extern lv_obj_t * uic_PanelModes;
extern lv_obj_t * uic_LabelModes;
extern lv_obj_t * uic_ButtonModes;
extern lv_obj_t * uic_PanelBackOption;
extern lv_obj_t * uic_ButtonBackOption;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

