// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B_BRANCO

#include "../ui.h"

lv_obj_t * uic_TextAreaQRSerial;
lv_obj_t * uic_TextAreaQRPage;
lv_obj_t * uic_KeyboardQR;
lv_obj_t * uic_ButtonBackInfoSetup;
lv_obj_t * uic_PanelBackInfoSetup;
lv_obj_t * uic_ScreenInfoSetup;
lv_obj_t * ui_ScreenInfoSetup = NULL;
lv_obj_t * ui_topBar7 = NULL;
lv_obj_t * ui_PanelBackInfoSetup = NULL;
lv_obj_t * ui_ButtonBackInfoSetup = NULL;
lv_obj_t * ui_KeyboardQR = NULL;
lv_obj_t * ui_TextAreaQRPage = NULL;
lv_obj_t * ui_TextAreaQRSerial = NULL;
// event funtions
void ui_event_ButtonBackInfoSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonBackInfoSetup_Clicked(e);
        _ui_screen_change(&ui_ScreenInfo, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenInfo_screen_init);
    }
}

void ui_event_KeyboardQR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        ui_event_QR_TextReady(e);
    }
}

void ui_event_TextAreaQRPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        ui_event_TextAreaQRPage_Focused(e);
    }
}

void ui_event_TextAreaQRSerial(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        ui_event_TextAreaQRSerial_Focused(e);
    }
}

// build funtions

void ui_ScreenInfoSetup_screen_init(void)
{
    ui_ScreenInfoSetup = lv_obj_create(NULL);
    lv_obj_set_style_bg_img_src(ui_ScreenInfoSetup, &img_base_azul, 0);
    lv_obj_set_style_bg_img_opa(ui_ScreenInfoSetup, LV_OPA_COVER, 0);
    lv_obj_clear_flag(ui_ScreenInfoSetup, LV_OBJ_FLAG_SCROLLABLE);

    ui_topBar7 = ui_topBar_create(ui_ScreenInfoSetup);
    lv_obj_set_x(ui_topBar7, 0);
    lv_obj_set_y(ui_topBar7, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBar7, UI_COMP_TOPBAR_LABELMENU), "Setup");

    ui_PanelBackInfoSetup = lv_obj_create(ui_ScreenInfoSetup);
    lv_obj_set_width(ui_PanelBackInfoSetup, 80);
    lv_obj_set_height(ui_PanelBackInfoSetup, 80);
    lv_obj_set_x(ui_PanelBackInfoSetup, 50);
    lv_obj_set_y(ui_PanelBackInfoSetup, 50);
    lv_obj_clear_flag(ui_PanelBackInfoSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBackInfoSetup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBackInfoSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBackInfoSetup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBackInfoSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackInfoSetup = lv_btn_create(ui_PanelBackInfoSetup);
    lv_obj_set_width(ui_ButtonBackInfoSetup, 80);
    lv_obj_set_height(ui_ButtonBackInfoSetup, 80);
    lv_obj_set_align(ui_ButtonBackInfoSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBackInfoSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBackInfoSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackInfoSetup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackInfoSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBackInfoSetup, &img_back_br, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardQR = lv_keyboard_create(ui_ScreenInfoSetup);
    lv_obj_set_width(ui_KeyboardQR, 1024);
    lv_obj_set_height(ui_KeyboardQR, 300);
    lv_obj_set_align(ui_KeyboardQR, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardQR, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_TextAreaQRPage = lv_textarea_create(ui_ScreenInfoSetup);
    lv_obj_set_width(ui_TextAreaQRPage, 500);
    lv_obj_set_height(ui_TextAreaQRPage, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaQRPage, 0);
    lv_obj_set_y(ui_TextAreaQRPage, -150);
    lv_obj_set_align(ui_TextAreaQRPage, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaQRPage, "Page");
    lv_textarea_set_one_line(ui_TextAreaQRPage, true);
    lv_obj_set_style_text_font(ui_TextAreaQRPage, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaQRSerial = lv_textarea_create(ui_ScreenInfoSetup);
    lv_obj_set_width(ui_TextAreaQRSerial, 500);
    lv_obj_set_height(ui_TextAreaQRSerial, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaQRSerial, 0);
    lv_obj_set_y(ui_TextAreaQRSerial, -60);
    lv_obj_set_align(ui_TextAreaQRSerial, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaQRSerial, "serial");
    lv_textarea_set_one_line(ui_TextAreaQRSerial, true);
    lv_obj_set_style_text_font(ui_TextAreaQRSerial, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonBackInfoSetup, ui_event_ButtonBackInfoSetup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardQR, ui_event_KeyboardQR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaQRPage, ui_event_TextAreaQRPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaQRSerial, ui_event_TextAreaQRSerial, LV_EVENT_ALL, NULL);
    uic_ScreenInfoSetup = ui_ScreenInfoSetup;
    uic_PanelBackInfoSetup = ui_PanelBackInfoSetup;
    uic_ButtonBackInfoSetup = ui_ButtonBackInfoSetup;
    uic_KeyboardQR = ui_KeyboardQR;
    uic_TextAreaQRPage = ui_TextAreaQRPage;
    uic_TextAreaQRSerial = ui_TextAreaQRSerial;

}

void ui_ScreenInfoSetup_screen_destroy(void)
{
    if(ui_ScreenInfoSetup) lv_obj_del(ui_ScreenInfoSetup);

    // NULL screen variables
    uic_ScreenInfoSetup = NULL;
    ui_ScreenInfoSetup = NULL;
    ui_topBar7 = NULL;
    uic_PanelBackInfoSetup = NULL;
    ui_PanelBackInfoSetup = NULL;
    uic_ButtonBackInfoSetup = NULL;
    ui_ButtonBackInfoSetup = NULL;
    uic_KeyboardQR = NULL;
    ui_KeyboardQR = NULL;
    uic_TextAreaQRPage = NULL;
    ui_TextAreaQRPage = NULL;
    uic_TextAreaQRSerial = NULL;
    ui_TextAreaQRSerial = NULL;

}
