// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B_BRANCO

#ifndef UI_SCREENINFOSETUP_H
#define UI_SCREENINFOSETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenInfoSetup
extern void ui_ScreenInfoSetup_screen_init(void);
extern void ui_ScreenInfoSetup_screen_destroy(void);
extern lv_obj_t * ui_ScreenInfoSetup;
extern lv_obj_t * ui_ScreenInfo1;
extern lv_obj_t * ui_topBar7;
extern lv_obj_t * ui_PanelBackInfoSetup;
extern void ui_event_ButtonBackInfoSetup(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackInfoSetup;
extern void ui_event_KeyboardQR(lv_event_t * e);
extern lv_obj_t * ui_KeyboardQR;
extern void ui_event_TextAreaQRPage(lv_event_t * e);
extern lv_obj_t * ui_TextAreaQRPage;
extern void ui_event_TextAreaQRSerial(lv_event_t * e);
extern lv_obj_t * ui_TextAreaQRSerial;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenInfoSetup;
extern lv_obj_t * uic_PanelBackInfoSetup;
extern lv_obj_t * uic_ButtonBackInfoSetup;
extern lv_obj_t * uic_KeyboardQR;
extern lv_obj_t * uic_TextAreaQRPage;
extern lv_obj_t * uic_TextAreaQRSerial;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

