// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_ButtonClean;
lv_obj_t * uic_PanelButtons;
lv_obj_t * uic_ButtonSettings;
//lv_obj_t * uic_PanelSet;
lv_obj_t * uic_PanelPrivate;
lv_obj_t * uic_LabelPrivateOff;
lv_obj_t * uic_LabelPrivateOn;
lv_obj_t * uic_SliderPrivate;
lv_obj_t * uic_PanelLock;
lv_obj_t * uic_LabelLockOff;
lv_obj_t * uic_LabelLockOn;
lv_obj_t * uic_SliderLock;
lv_obj_t * uic_PanelLed;
lv_obj_t * uic_SliderLed;
lv_obj_t * uic_PanelFan;
lv_obj_t * uic_ButtonRelax;
lv_obj_t * uic_ButtonPhone;
lv_obj_t * uic_topBar;
lv_obj_t * uic_ScreenMain;
lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_topBar = NULL;
lv_obj_t * ui_ButtonPhone = NULL;
lv_obj_t * ui_ButtonWork = NULL;
lv_obj_t * ui_ButtonRelax = NULL;
lv_obj_t * ui_SliderFan = NULL;
lv_obj_t * ui_PanelFan = NULL;
lv_obj_t * ui_SliderLed = NULL;
lv_obj_t * ui_PanelLed = NULL;
lv_obj_t * ui_SliderPrivate = NULL;
lv_obj_t * ui_LabelPrivateOn= NULL;
lv_obj_t * ui_LabelPrivateOff = NULL;
lv_obj_t * ui_PanelPrivate = NULL;
lv_obj_t * ui_SliderLock = NULL;
lv_obj_t * ui_LabelLockOn = NULL;
lv_obj_t * ui_LabelLockOff = NULL;
lv_obj_t * ui_PanelLock = NULL;
lv_obj_t * ui_ButtonSettings = NULL;
lv_obj_t * ui_PanelButtons = NULL;
lv_obj_t * ui_ButtonClean = NULL;
// event funtions
void ui_event_ButtonPhone(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonPhone_Clicked(e);
    }
}

void ui_event_ButtonWork(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonWork_Clicked(e);
    }
}

void ui_event_ButtonRelax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonRelax_Clicked(e);
    }
}

void ui_event_SliderFan_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_FanSlider_ValueChanged(e);
    }
}

void ui_event_SliderLed_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_LightSlider_ValueChanged(e);
    }
}

void ui_event_SliderPrivate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_PrivateSlider_ValueChanged(e);
    }
}

void ui_event_SliderLock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_LockSlider_ValueChanged(e);
    }
}

void ui_event_ButtonSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonSettings_Clicked(e);
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
    }
}

void ui_event_ButtonClean(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonClean_Clicked(e);
    }
}

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);

    lv_obj_set_style_bg_img_src(ui_ScreenMain, &img_base_azul, 0);
    lv_obj_set_style_bg_img_opa(ui_ScreenMain, LV_OPA_COVER, 0);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);

    ui_topBar = ui_topBar_create(ui_ScreenMain);
    lv_obj_set_x(ui_topBar, 0);
    lv_obj_set_y(ui_topBar, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBar, UI_COMP_TOPBAR_LABELMENU), "Home");

    ui_SliderFan = ui_Slider1_create(ui_ScreenMain);
    lv_obj_set_x(ui_SliderFan, -300);
    lv_obj_set_y(ui_SliderFan, 5);

    lv_obj_set_style_bg_color(ui_SliderFan, lv_color_hex(0xFBFBFB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderFan, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    //lv_obj_set_style_bg_grad_dir(ui_SliderFan, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_SliderFan, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SliderFan, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PanelFan = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelFan, 100);
    lv_obj_set_height(ui_PanelFan, 70);
    lv_obj_set_x(ui_PanelFan, -300);
    lv_obj_set_y(ui_PanelFan, -180);
    lv_obj_set_align(ui_PanelFan, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_opa(ui_PanelFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelFan, &img_fan_br, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_PanelFan, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_PanelFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderLed = ui_Slider1_create(ui_ScreenMain);
    lv_obj_set_x(ui_SliderLed, -100);
    lv_obj_set_y(ui_SliderLed, 0);

    lv_obj_set_style_bg_color(ui_SliderLed, lv_color_hex(0xFBFBFB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    //lv_obj_set_style_bg_grad_dir(ui_SliderLed, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_SliderLed, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SliderLed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PanelLed = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelLed, 100);
    lv_obj_set_height(ui_PanelLed, 70);
    lv_obj_set_x(ui_PanelLed, -100);
    lv_obj_set_y(ui_PanelLed, -180);
    lv_obj_set_align(ui_PanelLed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_opa(ui_PanelLed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelLed, &img_led_br, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_PanelLed, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_PanelLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderPrivate = lv_slider_create(ui_ScreenMain);
    lv_slider_set_range(ui_SliderPrivate, 0, 1);
    lv_slider_set_value(ui_SliderPrivate, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPrivate) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderPrivate, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPrivate, 120);
    lv_obj_set_height(ui_SliderPrivate, 240);
    lv_obj_set_x(ui_SliderPrivate, 110);
    lv_obj_set_y(ui_SliderPrivate, 0);
    lv_obj_set_align(ui_SliderPrivate, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderPrivate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPrivate, lv_color_hex(0x003446), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPrivate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderPrivate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderPrivate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderPrivate, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderPrivate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderPrivate, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPrivate, lv_color_hex(0x187790), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPrivate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderPrivate, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPrivate, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPrivate, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderPrivate, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderPrivate, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderPrivate, 50, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderPrivate, -60, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelPrivateOn = lv_label_create(ui_SliderPrivate);
    lv_obj_set_width(ui_LabelPrivateOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPrivateOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelPrivateOn, -75);
    lv_obj_set_x(ui_LabelPrivateOn, lv_pct(-4));
    lv_obj_set_align(ui_LabelPrivateOn, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelPrivateOn, "ON");
    lv_obj_set_style_text_color(ui_LabelPrivateOn, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPrivateOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPrivateOn, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPrivateOff = lv_label_create(ui_SliderPrivate);
    lv_obj_set_width(ui_LabelPrivateOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPrivateOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelPrivateOff, -30);
    lv_obj_set_x(ui_LabelPrivateOff, lv_pct(0));
    lv_obj_set_align(ui_LabelPrivateOff, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelPrivateOff, "OFF");
    lv_obj_set_style_text_color(ui_LabelPrivateOff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPrivateOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPrivateOff, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPrivate = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelPrivate, 100);
    lv_obj_set_height(ui_PanelPrivate, 60);
    lv_obj_set_x(ui_PanelPrivate, 110);
    lv_obj_set_y(ui_PanelPrivate, -180);
    lv_obj_set_align(ui_PanelPrivate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPrivate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_opa(ui_PanelPrivate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelPrivate, &img_priv_br, LV_PART_MAIN | LV_STATE_DEFAULT);
    //ui_object_set_themeable_style_property(ui_PanelPrivate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,_ui_theme_color_DEFAULT);
    //ui_object_set_themeable_style_property(ui_PanelPrivate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA _ui_theme_alpha_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPrivate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderLock = lv_slider_create(ui_ScreenMain);
    lv_slider_set_range(ui_SliderLock, 0, 1);
    lv_slider_set_value(ui_SliderLock, 0, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_SliderLock) == LV_SLIDER_MODE_RANGE)
    lv_slider_set_left_value(ui_SliderLock, 0, LV_ANIM_OFF);

    lv_obj_set_width(ui_SliderLock, 120);
    lv_obj_set_height(ui_SliderLock, 240);
    lv_obj_set_x(ui_SliderLock, 300); // cambia la posición X para que no se superponga
    lv_obj_set_y(ui_SliderLock, 0);
    lv_obj_set_align(ui_SliderLock, LV_ALIGN_CENTER);

    lv_obj_set_style_radius(ui_SliderLock, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderLock, lv_color_hex(0x003446), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderLock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderLock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderLock, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderLock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderLock, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderLock, lv_color_hex(0x187790), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLock, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderLock, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderLock, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLock, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderLock, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderLock, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderLock, 50, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderLock, -60, LV_PART_KNOB | LV_STATE_DEFAULT);
    // Labels ON/OFF
    ui_LabelLockOn = lv_label_create(ui_SliderLock);
    lv_obj_set_width(ui_LabelLockOn, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelLockOn, LV_SIZE_CONTENT);
    lv_obj_set_y(ui_LabelLockOn, -75);
    lv_obj_set_x(ui_LabelLockOn, lv_pct(-4));
    lv_obj_set_align(ui_LabelLockOn, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelLockOn, "ON");
    lv_obj_set_style_text_color(ui_LabelLockOn, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLockOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLockOn, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLockOff = lv_label_create(ui_SliderLock);
    lv_obj_set_width(ui_LabelLockOff, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelLockOff, LV_SIZE_CONTENT);
    lv_label_set_text(ui_LabelLockOff, "OFF");
    lv_obj_set_y(ui_LabelLockOff, -30);
    lv_obj_set_x(ui_LabelLockOff, lv_pct(0));
    lv_obj_set_align(ui_LabelLockOff, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_color(ui_LabelLockOff, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLockOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLockOff, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLock = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelLock, 100);
    lv_obj_set_height(ui_PanelLock, 70);
    lv_obj_set_x(ui_PanelLock, 300);
    lv_obj_set_y(ui_PanelLock, -180);
    lv_obj_set_align(ui_PanelLock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_opa(ui_PanelLock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelLock, &img_lock_br, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_PanelLock, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_PanelLock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
 
/* ============================= */
/*        PANEL BOTONES          */
/* ============================= */

ui_PanelButtons = lv_obj_create(ui_ScreenMain);
lv_obj_set_width(ui_PanelButtons, 900);
lv_obj_set_height(ui_PanelButtons, 120);
lv_obj_set_x(ui_PanelButtons, 0);
lv_obj_set_y(ui_PanelButtons, -20);
lv_obj_set_align(ui_PanelButtons, LV_ALIGN_BOTTOM_MID);

lv_obj_clear_flag(ui_PanelButtons, LV_OBJ_FLAG_SCROLLABLE);

lv_obj_set_style_bg_color(ui_PanelButtons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_PanelButtons, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

lv_obj_set_style_border_width(ui_PanelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_PanelButtons, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

lv_obj_set_style_shadow_opa(ui_PanelButtons, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_PanelButtons, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_PanelButtons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);


/* ============================= */
/*            CLEAN              */
/* ============================= */

   ui_ButtonClean = lv_btn_create(ui_PanelButtons);
   lv_obj_set_size(ui_ButtonClean, 120, 90);
   lv_obj_set_pos(ui_ButtonClean, -320, 0);
   lv_obj_set_align(ui_ButtonClean, LV_ALIGN_CENTER);

   lv_obj_clear_flag(ui_ButtonClean, LV_OBJ_FLAG_SCROLLABLE);

   lv_obj_set_style_bg_img_src(ui_ButtonClean, &img_clean_br, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(ui_ButtonClean, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_radius(ui_ButtonClean, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_add_flag(ui_ButtonClean, LV_OBJ_FLAG_CHECKABLE);

/* ============================= */
/*           PHONE               */
/* ============================= */

ui_ButtonPhone = lv_btn_create(ui_PanelButtons);
   lv_obj_set_size(ui_ButtonPhone, 120, 90);
   lv_obj_set_pos(ui_ButtonPhone, -160, 0);
   lv_obj_set_align(ui_ButtonPhone, LV_ALIGN_CENTER);

   lv_obj_clear_flag(ui_ButtonPhone, LV_OBJ_FLAG_SCROLLABLE);

   lv_obj_set_style_bg_img_src(ui_ButtonPhone, &img_phone_br, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(ui_ButtonPhone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_radius(ui_ButtonPhone, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_add_flag(ui_ButtonPhone, LV_OBJ_FLAG_CHECKABLE);

/* ============================= */
/*           WORK                */
/* ============================= */

   ui_ButtonWork = lv_btn_create(ui_PanelButtons);
   lv_obj_set_size(ui_ButtonWork, 120, 90);
   lv_obj_set_pos(ui_ButtonWork, 0, 0);
   lv_obj_set_align(ui_ButtonWork, LV_ALIGN_CENTER);

   lv_obj_clear_flag(ui_ButtonWork, LV_OBJ_FLAG_SCROLLABLE); 

   lv_obj_set_style_bg_img_src(ui_ButtonWork, &ui_img_work_png, LV_PART_MAIN);
   lv_obj_set_style_bg_img_recolor(ui_ButtonWork, lv_color_hex(0xFBFBFB), LV_PART_MAIN);
   lv_obj_set_style_bg_img_recolor_opa(ui_ButtonWork, LV_OPA_COVER, LV_PART_MAIN);
   lv_obj_set_style_bg_opa(ui_ButtonWork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_radius(ui_ButtonWork, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_add_flag(ui_ButtonWork, LV_OBJ_FLAG_CHECKABLE);

/* ============================= */
/*           RELAX               */
/* ============================= */

   ui_ButtonRelax = lv_btn_create(ui_PanelButtons);
   lv_obj_set_size(ui_ButtonRelax, 120, 90);
   lv_obj_set_pos(ui_ButtonRelax, 160, 0);
   lv_obj_set_align(ui_ButtonRelax, LV_ALIGN_CENTER);

   lv_obj_clear_flag(ui_ButtonRelax, LV_OBJ_FLAG_SCROLLABLE);

   lv_obj_set_style_bg_img_src(ui_ButtonRelax, &img_relax_br, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(ui_ButtonRelax, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_radius(ui_ButtonRelax, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_add_flag(ui_ButtonRelax, LV_OBJ_FLAG_CHECKABLE);

/* ============================= */
/*           SETTINGS            */
/* ============================= */

    ui_ButtonSettings = lv_btn_create(ui_PanelButtons);
    lv_obj_set_size(ui_ButtonSettings, 120, 90);
    lv_obj_set_pos(ui_ButtonSettings, 320, 0);
    lv_obj_set_align(ui_ButtonSettings, LV_ALIGN_CENTER);

    lv_obj_clear_flag(ui_ButtonSettings, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_set_style_bg_img_src(ui_ButtonSettings, &img_config_br, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ButtonSettings, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    lv_obj_add_event_cb(ui_ButtonPhone, ui_event_ButtonPhone, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonWork, ui_event_ButtonWork, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRelax, ui_event_ButtonRelax, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderFan, ui_event_SliderFan_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderLed, ui_event_SliderLed_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderPrivate, ui_event_SliderPrivate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderLock, ui_event_LockSlider_ValueChanged, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSettings, ui_event_ButtonSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonClean, ui_event_ButtonClean, LV_EVENT_ALL, NULL);
    uic_ScreenMain = ui_ScreenMain;
    uic_topBar = ui_topBar;
    uic_ButtonPhone = ui_ButtonPhone;
    uic_ButtonRelax = ui_ButtonRelax;
    uic_PanelFan = ui_PanelFan;
    uic_SliderLed = ui_SliderLed;
    uic_PanelLed = ui_PanelLed;
    uic_SliderPrivate = ui_SliderPrivate;
    uic_LabelPrivateOn = ui_LabelPrivateOn;
    uic_LabelPrivateOff = ui_LabelPrivateOff;
    uic_PanelPrivate = ui_PanelPrivate;
    uic_ButtonSettings = ui_ButtonSettings;
    uic_PanelButtons = ui_PanelButtons;
    uic_ButtonClean = ui_ButtonClean;

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    uic_ScreenMain = NULL;
    ui_ScreenMain = NULL;
    uic_topBar = NULL;
    ui_topBar = NULL;
    uic_ButtonPhone = NULL;
    ui_ButtonPhone = NULL;
    ui_ButtonWork = NULL;
    uic_ButtonRelax = NULL;
    ui_ButtonRelax = NULL;
    ui_SliderFan = NULL;
    uic_PanelFan = NULL;
    ui_PanelFan = NULL;
    uic_SliderLed = NULL;
    ui_SliderLed = NULL;
    uic_PanelLed = NULL;
    ui_PanelLed = NULL;
    uic_SliderPrivate = NULL;
    ui_SliderPrivate = NULL;
    uic_LabelPrivateOn = NULL;
    ui_LabelPrivateOn= NULL;
    uic_LabelPrivateOff = NULL;
    ui_LabelPrivateOff = NULL;
    uic_PanelPrivate = NULL;
    ui_PanelPrivate = NULL;
    uic_ButtonSettings = NULL;
    ui_ButtonSettings = NULL;
    uic_PanelButtons = NULL;
    ui_PanelButtons = NULL;
    uic_ButtonClean = NULL;
    ui_ButtonClean = NULL;

}
