// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_LabelPreviewDateTime;
lv_obj_t * uic_DropdownAmPm;
lv_obj_t * uic_LabelF;
lv_obj_t * uic_DropdownFormat;
lv_obj_t * uic_ContainerF;
lv_obj_t * uic_LabelM;
lv_obj_t * uic_RollerM;
lv_obj_t * uic_ContainerM;
lv_obj_t * uic_LabelH;
lv_obj_t * uic_RollerH;
lv_obj_t * uic_ContainerH;
lv_obj_t * uic_RollerDia;
lv_obj_t * uic_LabelDia;
lv_obj_t * uic_ContainerDia;
lv_obj_t * uic_RollerMes;
lv_obj_t * uic_LabelMes;
lv_obj_t * uic_ContainerMes;
lv_obj_t * uic_RollerAno;
lv_obj_t * uic_LabelAno;
lv_obj_t * uic_ContainerAno;
lv_obj_t * uic_ButtonBackDate;
lv_obj_t * uic_PanelBackDate;
lv_obj_t * uic_ButtonSaveDate;
lv_obj_t * uic_PanelSaveDate;
lv_obj_t * uic_topBarLight;
lv_obj_t * uic_ContainerLight;
lv_obj_t * uic_ScreenDate;
lv_obj_t * ui_ScreenDate = NULL;
lv_obj_t * ui_ContainerLight = NULL;
lv_obj_t * ui_topBarLight = NULL;
lv_obj_t * ui_PanelSaveDate = NULL;
lv_obj_t * ui_ButtonSaveDate = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_PanelBackDate = NULL;
lv_obj_t * ui_ButtonBackDate = NULL;
lv_obj_t * ui_ContainerAno = NULL;
lv_obj_t * ui_LabelAno = NULL;
lv_obj_t * ui_RollerAno = NULL;
lv_obj_t * ui_ContainerMes = NULL;
lv_obj_t * ui_LabelMes = NULL;
lv_obj_t * ui_RollerMes = NULL;
lv_obj_t * ui_ContainerDia = NULL;
lv_obj_t * ui_LabelDia = NULL;
lv_obj_t * ui_RollerDia = NULL;
lv_obj_t * ui_ContainerH = NULL;
lv_obj_t * ui_RollerH = NULL;
lv_obj_t * ui_LabelH = NULL;
lv_obj_t * ui_ContainerM = NULL;
lv_obj_t * ui_RollerM = NULL;
lv_obj_t * ui_LabelM = NULL;
lv_obj_t * ui_ContainerF = NULL;
lv_obj_t * ui_DropdownFormat = NULL;
lv_obj_t * ui_LabelF = NULL;
lv_obj_t * ui_DropdownAmPm = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_LabelPreviewDateTime = NULL;
// event funtions
void ui_event_ButtonSaveDate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonSaveDate_Clicked(e);
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ButtonBackDate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonBackDate_Clicked(e);
        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenOption_screen_init);
    }
}

void ui_event_RollerAno(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_RollerAno_ValueChanged(e);
    }
}

void ui_event_RollerMes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_RollerMes_ValueChanged(e);
    }
}

void ui_event_RollerDia(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_RollerDia_ValueChanged(e);
    }
}

void ui_event_RollerH(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_RollerH_ValueChanged(e);
    }
}

void ui_event_RollerM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_RollerM_ValueChanged(e);
    }
}

void ui_event_DropdownFormat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_DropdownFormat_ValueChanged(e);
    }
}

void ui_event_DropdownAmPm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_DropdownAmPm_ValueChanged(e);
    }
}

// build funtions

void ui_ScreenDate_screen_init(void)
{
    ui_ScreenDate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenDate, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_set_style_radius(ui_ScreenDate, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenDate, lv_color_hex(0x110E0E), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenDate, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenDate, lv_color_hex(0x535353), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ContainerLight = lv_obj_create(ui_ScreenDate);
    lv_obj_remove_style_all(ui_ContainerLight);
    lv_obj_set_width(ui_ContainerLight, lv_pct(100));
    lv_obj_set_height(ui_ContainerLight, lv_pct(100));
    lv_obj_set_align(ui_ContainerLight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLight,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBarLight = ui_topBar_create(ui_ContainerLight);
    lv_obj_set_x(ui_topBarLight, 0);
    lv_obj_set_y(ui_topBarLight, 20);

    lv_label_set_text(ui_comp_get_child(ui_topBarLight, UI_COMP_TOPBAR_LABELMENU), "Date");

    ui_PanelSaveDate = lv_obj_create(ui_ContainerLight);
    lv_obj_set_width(ui_PanelSaveDate, 100);
    lv_obj_set_height(ui_PanelSaveDate, 60);
    lv_obj_set_x(ui_PanelSaveDate, -100);
    lv_obj_set_y(ui_PanelSaveDate, -50);
    lv_obj_set_align(ui_PanelSaveDate, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_PanelSaveDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSaveDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSaveDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelSaveDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_PanelSaveDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Dark);

    ui_ButtonSaveDate = lv_btn_create(ui_PanelSaveDate);
    lv_obj_set_width(ui_ButtonSaveDate, 100);
    lv_obj_set_height(ui_ButtonSaveDate, 50);
    lv_obj_set_align(ui_ButtonSaveDate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSaveDate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSaveDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonSaveDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonSaveDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonSaveDate, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ButtonSaveDate);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Save");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBackDate = lv_obj_create(ui_ContainerLight);
    lv_obj_set_width(ui_PanelBackDate, 50);
    lv_obj_set_height(ui_PanelBackDate, 50);
    lv_obj_set_x(ui_PanelBackDate, 50);
    lv_obj_set_y(ui_PanelBackDate, 50);
    lv_obj_clear_flag(ui_PanelBackDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBackDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBackDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBackDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBackDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackDate = lv_btn_create(ui_PanelBackDate);
    lv_obj_set_width(ui_ButtonBackDate, 100);
    lv_obj_set_height(ui_ButtonBackDate, 50);
    lv_obj_set_align(ui_ButtonBackDate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBackDate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBackDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBackDate, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonBackDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonBackDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_border_color(ui_ButtonBackDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonBackDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerAno = lv_obj_create(ui_ContainerLight);
    lv_obj_remove_style_all(ui_ContainerAno);
    lv_obj_set_width(ui_ContainerAno, 120);
    lv_obj_set_height(ui_ContainerAno, 150);
    lv_obj_set_x(ui_ContainerAno, -100);
    lv_obj_set_y(ui_ContainerAno, 0);
    lv_obj_set_align(ui_ContainerAno, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerAno, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAno = lv_label_create(ui_ContainerAno);
    lv_obj_set_width(ui_LabelAno, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAno, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelAno, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelAno, "Year");
    lv_obj_set_style_text_font(ui_LabelAno, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerAno = lv_roller_create(ui_ContainerAno);
    lv_roller_set_options(ui_RollerAno, "2024\n2025\n2026\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerAno, 100);
    lv_obj_set_height(ui_RollerAno, 100);
    lv_obj_set_align(ui_RollerAno, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_RollerAno, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(ui_RollerAno, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ContainerMes = lv_obj_create(ui_ContainerLight);
    lv_obj_remove_style_all(ui_ContainerMes);
    lv_obj_set_width(ui_ContainerMes, 120);
    lv_obj_set_height(ui_ContainerMes, 150);
    lv_obj_set_x(ui_ContainerMes, -220);
    lv_obj_set_y(ui_ContainerMes, 0);
    lv_obj_set_align(ui_ContainerMes, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMes, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMes = lv_label_create(ui_ContainerMes);
    lv_obj_set_width(ui_LabelMes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMes, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelMes, "Mes");
    lv_obj_set_style_text_font(ui_LabelMes, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerMes = lv_roller_create(ui_ContainerMes);
    lv_roller_set_options(ui_RollerMes, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerMes, 100);
    lv_obj_set_height(ui_RollerMes, 100);
    lv_obj_set_align(ui_RollerMes, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_style_text_font(ui_RollerMes, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ContainerDia = lv_obj_create(ui_ContainerLight);
    lv_obj_remove_style_all(ui_ContainerDia);
    lv_obj_set_width(ui_ContainerDia, 120);
    lv_obj_set_height(ui_ContainerDia, 150);
    lv_obj_set_x(ui_ContainerDia, -340);
    lv_obj_set_y(ui_ContainerDia, 0);
    lv_obj_set_align(ui_ContainerDia, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerDia, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDia = lv_label_create(ui_ContainerDia);
    lv_obj_set_width(ui_LabelDia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDia, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelDia, "Dia");
    lv_obj_set_style_text_font(ui_LabelDia, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerDia = lv_roller_create(ui_ContainerDia);
    lv_roller_set_options(ui_RollerDia,
                          "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerDia, 100);
    lv_obj_set_height(ui_RollerDia, 100);
    lv_obj_set_align(ui_RollerDia, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_RollerDia, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(ui_RollerDia, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ContainerH = lv_obj_create(ui_ContainerLight);
    lv_obj_remove_style_all(ui_ContainerH);
    lv_obj_set_width(ui_ContainerH, 120);
    lv_obj_set_height(ui_ContainerH, 150);
    lv_obj_set_x(ui_ContainerH, 50);
    lv_obj_set_y(ui_ContainerH, 0);
    lv_obj_set_align(ui_ContainerH, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerH, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerH = lv_roller_create(ui_ContainerH);
    lv_roller_set_options(ui_RollerH, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerH, 100);
    lv_obj_set_height(ui_RollerH, 100);
    lv_obj_set_align(ui_RollerH, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_RollerH, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(ui_RollerH, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LabelH = lv_label_create(ui_ContainerH);
    lv_obj_set_width(ui_LabelH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelH, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelH, "Hour");
    lv_obj_set_style_text_font(ui_LabelH, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerM = lv_obj_create(ui_ContainerLight);
    lv_obj_remove_style_all(ui_ContainerM);
    lv_obj_set_width(ui_ContainerM, 120);
    lv_obj_set_height(ui_ContainerM, 150);
    lv_obj_set_x(ui_ContainerM, 170);
    lv_obj_set_y(ui_ContainerM, 0);
    lv_obj_set_align(ui_ContainerM, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerM = lv_roller_create(ui_ContainerM);
    lv_roller_set_options(ui_RollerM,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerM, 100);
    lv_obj_set_height(ui_RollerM, 100);
    lv_obj_set_align(ui_RollerM, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_RollerM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(ui_RollerM, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LabelM = lv_label_create(ui_ContainerM);
    lv_obj_set_width(ui_LabelM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelM, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelM, "Minutes");
    lv_obj_set_style_text_font(ui_LabelM, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerF = lv_obj_create(ui_ContainerLight);
    lv_obj_remove_style_all(ui_ContainerF);
    lv_obj_set_width(ui_ContainerF, 120);
    lv_obj_set_height(ui_ContainerF, 160);
    lv_obj_set_x(ui_ContainerF, 300);
    lv_obj_set_y(ui_ContainerF, 8);
    lv_obj_set_align(ui_ContainerF, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerF, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropdownFormat = lv_dropdown_create(ui_ContainerF);
    lv_dropdown_set_options(ui_DropdownFormat, "12H\n24H");
    lv_obj_set_width(ui_DropdownFormat, 100);
    lv_obj_set_height(ui_DropdownFormat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownFormat, 0);
    lv_obj_set_y(ui_DropdownFormat, -13);
    lv_obj_set_align(ui_DropdownFormat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownFormat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownFormat, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_DropdownFormat, &lv_font_montserrat_24, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownFormat), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownFormat), &lv_font_montserrat_28,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LabelF = lv_label_create(ui_ContainerF);
    lv_obj_set_width(ui_LabelF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelF, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelF, "Format");
    lv_obj_set_style_text_font(ui_LabelF, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownAmPm = lv_dropdown_create(ui_ContainerF);
    lv_dropdown_set_options(ui_DropdownAmPm, "AM \nPM ");
    lv_obj_set_width(ui_DropdownAmPm, 100);
    lv_obj_set_height(ui_DropdownAmPm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownAmPm, 0);
    lv_obj_set_y(ui_DropdownAmPm, -4);
    lv_obj_set_align(ui_DropdownAmPm, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_DropdownAmPm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownAmPm, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_DropdownAmPm, &lv_font_montserrat_24, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownAmPm), &lv_font_montserrat_28,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownAmPm), &lv_font_montserrat_28,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_ContainerLight);
    lv_obj_set_width(ui_Panel3, 300);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 100);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPreviewDateTime = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelPreviewDateTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreviewDateTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPreviewDateTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreviewDateTime, "--/--/---- --:--");
    lv_obj_set_style_text_font(ui_LabelPreviewDateTime, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonSaveDate, ui_event_ButtonSaveDate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBackDate, ui_event_ButtonBackDate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerAno, ui_event_RollerAno, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerMes, ui_event_RollerMes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerDia, ui_event_RollerDia, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerH, ui_event_RollerH, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerM, ui_event_RollerM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownFormat, ui_event_DropdownFormat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownAmPm, ui_event_DropdownAmPm, LV_EVENT_ALL, NULL);
    uic_ScreenDate = ui_ScreenDate;
    uic_ContainerLight = ui_ContainerLight;
    uic_topBarLight = ui_topBarLight;
    uic_PanelSaveDate = ui_PanelSaveDate;
    uic_ButtonSaveDate = ui_ButtonSaveDate;
    uic_PanelBackDate = ui_PanelBackDate;
    uic_ButtonBackDate = ui_ButtonBackDate;
    uic_ContainerAno = ui_ContainerAno;
    uic_LabelAno = ui_LabelAno;
    uic_RollerAno = ui_RollerAno;
    uic_ContainerMes = ui_ContainerMes;
    uic_LabelMes = ui_LabelMes;
    uic_RollerMes = ui_RollerMes;
    uic_ContainerDia = ui_ContainerDia;
    uic_LabelDia = ui_LabelDia;
    uic_RollerDia = ui_RollerDia;
    uic_ContainerH = ui_ContainerH;
    uic_RollerH = ui_RollerH;
    uic_LabelH = ui_LabelH;
    uic_ContainerM = ui_ContainerM;
    uic_RollerM = ui_RollerM;
    uic_LabelM = ui_LabelM;
    uic_ContainerF = ui_ContainerF;
    uic_DropdownFormat = ui_DropdownFormat;
    uic_LabelF = ui_LabelF;
    uic_DropdownAmPm = ui_DropdownAmPm;
    uic_LabelPreviewDateTime = ui_LabelPreviewDateTime;

}

void ui_ScreenDate_screen_destroy(void)
{
    if(ui_ScreenDate) lv_obj_del(ui_ScreenDate);

    // NULL screen variables
    uic_ScreenDate = NULL;
    ui_ScreenDate = NULL;
    uic_ContainerLight = NULL;
    ui_ContainerLight = NULL;
    uic_topBarLight = NULL;
    ui_topBarLight = NULL;
    uic_PanelSaveDate = NULL;
    ui_PanelSaveDate = NULL;
    uic_ButtonSaveDate = NULL;
    ui_ButtonSaveDate = NULL;
    ui_Label10 = NULL;
    uic_PanelBackDate = NULL;
    ui_PanelBackDate = NULL;
    uic_ButtonBackDate = NULL;
    ui_ButtonBackDate = NULL;
    uic_ContainerAno = NULL;
    ui_ContainerAno = NULL;
    uic_LabelAno = NULL;
    ui_LabelAno = NULL;
    uic_RollerAno = NULL;
    ui_RollerAno = NULL;
    uic_ContainerMes = NULL;
    ui_ContainerMes = NULL;
    uic_LabelMes = NULL;
    ui_LabelMes = NULL;
    uic_RollerMes = NULL;
    ui_RollerMes = NULL;
    uic_ContainerDia = NULL;
    ui_ContainerDia = NULL;
    uic_LabelDia = NULL;
    ui_LabelDia = NULL;
    uic_RollerDia = NULL;
    ui_RollerDia = NULL;
    uic_ContainerH = NULL;
    ui_ContainerH = NULL;
    uic_RollerH = NULL;
    ui_RollerH = NULL;
    uic_LabelH = NULL;
    ui_LabelH = NULL;
    uic_ContainerM = NULL;
    ui_ContainerM = NULL;
    uic_RollerM = NULL;
    ui_RollerM = NULL;
    uic_LabelM = NULL;
    ui_LabelM = NULL;
    uic_ContainerF = NULL;
    ui_ContainerF = NULL;
    uic_DropdownFormat = NULL;
    ui_DropdownFormat = NULL;
    uic_LabelF = NULL;
    ui_LabelF = NULL;
    uic_DropdownAmPm = NULL;
    ui_DropdownAmPm = NULL;
    ui_Panel3 = NULL;
    uic_LabelPreviewDateTime = NULL;
    ui_LabelPreviewDateTime = NULL;

}
