// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_topBarSettings;
extern void ui_event_TextAreaPinSettings(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPinSettings;
extern lv_obj_t * ui_PanelNumber1;
extern lv_obj_t * ui_PanelBackHome;
extern void ui_event_ButtonBackHome(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackHome;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenSettings;
extern lv_obj_t * uic_topBarSettings;
extern lv_obj_t * uic_TextAreaPinSettings;
extern lv_obj_t * uic_PanelNumber1;
extern lv_obj_t * uic_PanelBackHome;
extern lv_obj_t * uic_ButtonBackHome;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

