// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENDATE_H
#define UI_SCREENDATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDate
extern void ui_ScreenDate_screen_init(void);
extern void ui_ScreenDate_screen_destroy(void);
extern lv_obj_t * ui_ScreenDate;
extern lv_obj_t * ui_ContainerLight;
extern lv_obj_t * ui_topBarLight;
extern lv_obj_t * ui_PanelSaveDate;
extern void ui_event_ButtonSaveDate(lv_event_t * e);
extern lv_obj_t * ui_ButtonSaveDate;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_PanelBackDate;
extern void ui_event_ButtonBackDate(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackDate;
extern lv_obj_t * ui_ContainerAno;
extern lv_obj_t * ui_LabelAno;
extern void ui_event_RollerAno(lv_event_t * e);
extern lv_obj_t * ui_RollerAno;
extern lv_obj_t * ui_ContainerMes;
extern lv_obj_t * ui_LabelMes;
extern void ui_event_RollerMes(lv_event_t * e);
extern lv_obj_t * ui_RollerMes;
extern lv_obj_t * ui_ContainerDia;
extern lv_obj_t * ui_LabelDia;
extern void ui_event_RollerDia(lv_event_t * e);
extern lv_obj_t * ui_RollerDia;
extern lv_obj_t * ui_ContainerH;
extern void ui_event_RollerH(lv_event_t * e);
extern lv_obj_t * ui_RollerH;
extern lv_obj_t * ui_LabelH;
extern lv_obj_t * ui_ContainerM;
extern void ui_event_RollerM(lv_event_t * e);
extern lv_obj_t * ui_RollerM;
extern lv_obj_t * ui_LabelM;
extern lv_obj_t * ui_ContainerF;
extern void ui_event_DropdownFormat(lv_event_t * e);
extern lv_obj_t * ui_DropdownFormat;
extern lv_obj_t * ui_LabelF;
extern void ui_event_DropdownAmPm(lv_event_t * e);
extern lv_obj_t * ui_DropdownAmPm;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_LabelPreviewDateTime;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenDate;
extern lv_obj_t * uic_ContainerLight;
extern lv_obj_t * uic_topBarLight;
extern lv_obj_t * uic_PanelSaveDate;
extern lv_obj_t * uic_ButtonSaveDate;
extern lv_obj_t * uic_PanelBackDate;
extern lv_obj_t * uic_ButtonBackDate;
extern lv_obj_t * uic_ContainerAno;
extern lv_obj_t * uic_LabelAno;
extern lv_obj_t * uic_RollerAno;
extern lv_obj_t * uic_ContainerMes;
extern lv_obj_t * uic_LabelMes;
extern lv_obj_t * uic_RollerMes;
extern lv_obj_t * uic_ContainerDia;
extern lv_obj_t * uic_LabelDia;
extern lv_obj_t * uic_RollerDia;
extern lv_obj_t * uic_ContainerH;
extern lv_obj_t * uic_RollerH;
extern lv_obj_t * uic_LabelH;
extern lv_obj_t * uic_ContainerM;
extern lv_obj_t * uic_RollerM;
extern lv_obj_t * uic_LabelM;
extern lv_obj_t * uic_ContainerF;
extern lv_obj_t * uic_DropdownFormat;
extern lv_obj_t * uic_LabelF;
extern lv_obj_t * uic_DropdownAmPm;
extern lv_obj_t * uic_LabelPreviewDateTime;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

