// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_ButtonBackPin;
lv_obj_t * uic_PanelBackPin;
lv_obj_t * uic_TextAreaPinAdvanced;
lv_obj_t * uic_LabelPinAdvanced;
lv_obj_t * uic_ContainerPinAdvanced;
lv_obj_t * uic_TextAreaPinUser;
lv_obj_t * uic_LabelPinUser;
lv_obj_t * uic_ContainerPinUser;
lv_obj_t * uic_ScreenPin;
lv_obj_t * ui_ScreenPin = NULL;
lv_obj_t * ui_topBar2 = NULL;
lv_obj_t * ui_PanelNumber2 = NULL;
lv_obj_t * ui_LabelPinUser = NULL;
lv_obj_t * ui_TextAreaPinUser = NULL;
lv_obj_t * ui_ContainerPinAdvanced = NULL;
lv_obj_t * ui_ContainerPinUser = NULL;
lv_obj_t * ui_LabelPinAdvanced = NULL;
lv_obj_t * ui_TextAreaPinAdvanced = NULL;
lv_obj_t * ui_PanelBackPin = NULL;
lv_obj_t * ui_ButtonBackPin = NULL;
// event funtions
void ui_event_TextAreaPinUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_PinUser_Clicked(e);
    }
}

void ui_event_TextAreaPinAdvanced(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_PinAdvanced_Clicked(e);
    }
}

void ui_event_ButtonBackPin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonBackPin_Clicked(e);
        _ui_screen_change(&ui_ScreenAdvanced, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenAdvanced_screen_init);
    }
}

// build funtions

void ui_ScreenPin_screen_init(void)
{
    ui_ScreenPin = lv_obj_create(NULL);
    lv_obj_set_style_bg_img_src(ui_ScreenPin, &img_base_azul, 0);
    lv_obj_set_style_bg_img_opa(ui_ScreenPin, LV_OPA_COVER, 0);
    lv_obj_clear_flag(ui_ScreenPin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topBar2 = ui_topBar_create(ui_ScreenPin);
    lv_obj_set_x(ui_topBar2, 0);
    lv_obj_set_y(ui_topBar2, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBar2, UI_COMP_TOPBAR_LABELMENU), "Pin Setup");

    ui_PanelNumber2 = ui_PanelNumber_create(ui_ScreenPin);
    lv_obj_set_x(ui_PanelNumber2, -44);
    lv_obj_set_y(ui_PanelNumber2, 20);
    lv_obj_set_align(ui_PanelNumber2, LV_ALIGN_RIGHT_MID);


    ui_ContainerPinUser = lv_obj_create(ui_ScreenPin);
    lv_obj_remove_style_all(ui_ContainerPinUser);
    lv_obj_set_width(ui_ContainerPinUser, 165);
    lv_obj_set_height(ui_ContainerPinUser, 157);
    lv_obj_set_x(ui_ContainerPinUser, -280);
    lv_obj_set_y(ui_ContainerPinUser, -100);
    lv_obj_set_align(ui_ContainerPinUser, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPinUser, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPinUser = lv_label_create(ui_ContainerPinUser);
    lv_obj_set_width(ui_LabelPinUser, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPinUser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPinUser, 0);
    lv_obj_set_y(ui_LabelPinUser, -30);
    lv_obj_set_align(ui_LabelPinUser, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPinUser, "User Pin");
    lv_obj_set_style_text_font(ui_LabelPinUser, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaPinUser = lv_textarea_create(ui_ContainerPinUser);
    lv_obj_set_width(ui_TextAreaPinUser, 150);
    lv_obj_set_height(ui_TextAreaPinUser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextAreaPinUser, 0);
    lv_obj_set_y(ui_TextAreaPinUser, 70);
    lv_obj_set_align(ui_TextAreaPinUser, LV_ALIGN_TOP_MID);
    lv_textarea_set_max_length(ui_TextAreaPinUser, 4);
    lv_textarea_set_placeholder_text(ui_TextAreaPinUser, "1234");
    lv_textarea_set_one_line(ui_TextAreaPinUser, true);
    lv_textarea_set_password_mode(ui_TextAreaPinUser, true);
    lv_obj_add_flag(ui_TextAreaPinUser, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    ui_object_set_themeable_style_property(ui_TextAreaPinUser, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_TextAreaPinUser, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_align(ui_TextAreaPinUser, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPinUser, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_TextAreaPinUser, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_TextAreaPinUser, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_align(ui_TextAreaPinUser, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPinUser, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_TextAreaPinUser, LV_PART_CURSOR | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_TextAreaPinUser, LV_PART_CURSOR | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_align(ui_TextAreaPinUser, LV_TEXT_ALIGN_CENTER, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPinUser, &lv_font_montserrat_28, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_TextAreaPinUser, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_DEFAULT);
    ui_object_set_themeable_style_property(ui_TextAreaPinUser, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextAreaPinUser, 0, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextAreaPinUser, 0, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextAreaPinUser, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPinUser, &lv_font_montserrat_28, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_ContainerPinAdvanced = lv_obj_create(ui_ScreenPin);
    lv_obj_remove_style_all(ui_ContainerPinAdvanced);
    lv_obj_set_width(ui_ContainerPinAdvanced, 165);
    lv_obj_set_height(ui_ContainerPinAdvanced, 157);
    lv_obj_set_x(ui_ContainerPinAdvanced, -280);
    lv_obj_set_y(ui_ContainerPinAdvanced, 100);
    lv_obj_set_align(ui_ContainerPinAdvanced, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPinAdvanced, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPinAdvanced = lv_label_create(ui_ContainerPinAdvanced);
    lv_obj_set_width(ui_LabelPinAdvanced, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPinAdvanced, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPinAdvanced, 0);
    lv_obj_set_y(ui_LabelPinAdvanced, -30);
    lv_obj_set_align(ui_LabelPinAdvanced, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPinAdvanced, "Advanced Pin");
    lv_obj_set_style_text_font(ui_LabelPinAdvanced, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaPinAdvanced = lv_textarea_create(ui_ContainerPinAdvanced);
    lv_obj_set_width(ui_TextAreaPinAdvanced, 150);
    lv_obj_set_height(ui_TextAreaPinAdvanced, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextAreaPinAdvanced, 0);
    lv_obj_set_y(ui_TextAreaPinAdvanced, 70);
    lv_obj_set_align(ui_TextAreaPinAdvanced, LV_ALIGN_TOP_MID);
    lv_textarea_set_max_length(ui_TextAreaPinAdvanced, 4);
    lv_textarea_set_placeholder_text(ui_TextAreaPinAdvanced, "4567");
    lv_textarea_set_one_line(ui_TextAreaPinAdvanced, true);
    lv_textarea_set_password_mode(ui_TextAreaPinAdvanced, true);
    lv_obj_add_flag(ui_TextAreaPinAdvanced, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    ui_object_set_themeable_style_property(ui_TextAreaPinAdvanced, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_TextAreaPinAdvanced, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_align(ui_TextAreaPinAdvanced, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPinAdvanced, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_TextAreaPinAdvanced, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_TextAreaPinAdvanced, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_align(ui_TextAreaPinAdvanced, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPinAdvanced, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_TextAreaPinAdvanced, LV_PART_CURSOR | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_TextAreaPinAdvanced, LV_PART_CURSOR | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_align(ui_TextAreaPinAdvanced, LV_TEXT_ALIGN_CENTER, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPinAdvanced, &lv_font_montserrat_28, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_TextAreaPinAdvanced, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_DEFAULT);
    ui_object_set_themeable_style_property(ui_TextAreaPinAdvanced, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextAreaPinAdvanced, 0, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextAreaPinAdvanced, 0, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextAreaPinAdvanced, LV_TEXT_ALIGN_CENTER,
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPinAdvanced, &lv_font_montserrat_28,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_PanelBackPin = lv_obj_create(ui_ScreenPin);
    lv_obj_set_width(ui_PanelBackPin, 80);
    lv_obj_set_height(ui_PanelBackPin, 80);
    lv_obj_set_x(ui_PanelBackPin, 50);
    lv_obj_set_y(ui_PanelBackPin, 50);
    lv_obj_clear_flag(ui_PanelBackPin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBackPin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBackPin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBackPin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBackPin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackPin = lv_btn_create(ui_PanelBackPin);
    lv_obj_set_width(ui_ButtonBackPin, 80);
    lv_obj_set_height(ui_ButtonBackPin, 80);
    lv_obj_set_align(ui_ButtonBackPin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBackPin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBackPin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackPin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackPin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBackPin, &img_back_br, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonBackPin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonBackPin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_border_color(ui_ButtonBackPin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonBackPin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextAreaPinUser, ui_event_TextAreaPinUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaPinAdvanced, ui_event_TextAreaPinAdvanced, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBackPin, ui_event_ButtonBackPin, LV_EVENT_ALL, NULL);
    uic_ScreenPin = ui_ScreenPin;
    uic_ContainerPinUser = ui_ContainerPinUser;
    uic_LabelPinUser = ui_LabelPinUser;
    uic_TextAreaPinUser = ui_TextAreaPinUser;
    uic_ContainerPinAdvanced = ui_ContainerPinAdvanced;
    uic_LabelPinAdvanced = ui_LabelPinAdvanced;
    uic_TextAreaPinAdvanced = ui_TextAreaPinAdvanced;
    uic_PanelBackPin = ui_PanelBackPin;
    uic_ButtonBackPin = ui_ButtonBackPin;

}

void ui_ScreenPin_screen_destroy(void)
{
    if(ui_ScreenPin) lv_obj_del(ui_ScreenPin);

    // NULL screen variables
    ui_ScreenPin = NULL;
    ui_topBar2 = NULL;
    ui_PanelNumber2 = NULL;
    uic_ContainerPinUser = NULL;
    ui_ContainerPinUser = NULL;
    uic_LabelPinUser = NULL;
    ui_LabelPinUser = NULL;
    uic_TextAreaPinUser = NULL;
    ui_TextAreaPinUser = NULL;
    uic_ContainerPinAdvanced = NULL;
    ui_ContainerPinAdvanced = NULL;
    uic_LabelPinAdvanced = NULL;
    ui_LabelPinAdvanced = NULL;
    uic_TextAreaPinAdvanced = NULL;
    ui_TextAreaPinAdvanced = NULL;
    uic_PanelBackPin = NULL;
    ui_PanelBackPin = NULL;
    uic_ButtonBackPin = NULL;
    ui_ButtonBackPin = NULL;

}
