// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_ButtonBackHome;
lv_obj_t * uic_PanelBackHome;
lv_obj_t * uic_PanelNumber1;
lv_obj_t * uic_TextAreaPinSettings;
lv_obj_t * uic_topBarSettings;
lv_obj_t * uic_ScreenSettings;
lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_topBarSettings = NULL;
lv_obj_t * ui_TextAreaPinSettings = NULL;
lv_obj_t * ui_PanelNumber1 = NULL;
lv_obj_t * ui_PanelBackHome = NULL;
lv_obj_t * ui_ButtonBackHome = NULL;
// event funtions
void ui_event_TextAreaPinSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        ui_event_TextAreaPinSettings_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ui_event_TextAreaPinSettings_Defocused(e);
    }
}

void ui_event_ButtonBackHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonBackHome_Clicked(e);
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
    }
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_set_style_bg_img_src(ui_ScreenSettings, &img_base_azul, 0);
    lv_obj_set_style_bg_img_opa(ui_ScreenSettings, LV_OPA_COVER, 0);
    lv_obj_clear_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);

    ui_topBarSettings = ui_topBar_create(ui_ScreenSettings);
    lv_obj_set_x(ui_topBarSettings, 0);
    lv_obj_set_y(ui_topBarSettings, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBarSettings, UI_COMP_TOPBAR_LABELMENU), "Settings");

    ui_TextAreaPinSettings = lv_textarea_create(ui_ScreenSettings);
    lv_obj_set_width(ui_TextAreaPinSettings, 150);
    lv_obj_set_height(ui_TextAreaPinSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextAreaPinSettings, 0);
    lv_obj_set_y(ui_TextAreaPinSettings, 100);
    lv_obj_set_align(ui_TextAreaPinSettings, LV_ALIGN_TOP_MID);
    lv_textarea_set_max_length(ui_TextAreaPinSettings, 4);
    lv_textarea_set_placeholder_text(ui_TextAreaPinSettings, "PIN   ");
    lv_textarea_set_one_line(ui_TextAreaPinSettings, true);
    lv_textarea_set_password_mode(ui_TextAreaPinSettings, true);
    lv_obj_add_state(ui_TextAreaPinSettings, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_TextAreaPinSettings, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_font(ui_TextAreaPinSettings, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextAreaPinSettings, 0, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextAreaPinSettings, 0, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TextAreaPinSettings, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaPinSettings, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaPinSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaPinSettings, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaPinSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaPinSettings, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaPinSettings, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextAreaPinSettings, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TextAreaPinSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextAreaPinSettings, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNumber1 = ui_PanelNumber_create(ui_ScreenSettings);
    lv_obj_set_x(ui_PanelNumber1, 0);
    lv_obj_set_y(ui_PanelNumber1, 80);


    ui_PanelBackHome = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelBackHome, 80);
    lv_obj_set_height(ui_PanelBackHome, 80);
    lv_obj_set_x(ui_PanelBackHome, 50);
    lv_obj_set_y(ui_PanelBackHome, 50);
    lv_obj_clear_flag(ui_PanelBackHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBackHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBackHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBackHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBackHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackHome = lv_btn_create(ui_PanelBackHome);
    lv_obj_set_width(ui_ButtonBackHome, 80);
    lv_obj_set_height(ui_ButtonBackHome, 80);
    lv_obj_set_align(ui_ButtonBackHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBackHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBackHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBackHome, &img_back_br, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonBackHome, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonBackHome, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_border_color(ui_ButtonBackHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonBackHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextAreaPinSettings, ui_event_TextAreaPinSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBackHome, ui_event_ButtonBackHome, LV_EVENT_ALL, NULL);
    uic_ScreenSettings = ui_ScreenSettings;
    uic_topBarSettings = ui_topBarSettings;
    uic_TextAreaPinSettings = ui_TextAreaPinSettings;
    uic_PanelNumber1 = ui_PanelNumber1;
    uic_PanelBackHome = ui_PanelBackHome;
    uic_ButtonBackHome = ui_ButtonBackHome;

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    uic_ScreenSettings = NULL;
    ui_ScreenSettings = NULL;
    uic_topBarSettings = NULL;
    ui_topBarSettings = NULL;
    uic_TextAreaPinSettings = NULL;
    ui_TextAreaPinSettings = NULL;
    uic_PanelNumber1 = NULL;
    ui_PanelNumber1 = NULL;
    uic_PanelBackHome = NULL;
    ui_PanelBackHome = NULL;
    uic_ButtonBackHome = NULL;
    ui_ButtonBackHome = NULL;

}
