// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENCONTROL_H
#define UI_SCREENCONTROL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenControl
extern void ui_ScreenControl_screen_init(void);
extern void ui_ScreenControl_screen_destroy(void);
extern lv_obj_t * ui_ScreenControl;
extern lv_obj_t * ui_PanelBackControl;
extern void ui_event_ButtonBackControl(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackControl;
extern lv_obj_t * ui_Container1;
extern void ui_event_SwitchIR(lv_event_t * e);
extern lv_obj_t * ui_SwitchIR;
extern lv_obj_t * ui_LabelIR;
extern lv_obj_t * ui_topBar6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenControl;
extern lv_obj_t * uic_PanelBackControl;
extern lv_obj_t * uic_ButtonBackControl;
extern lv_obj_t * uic_SwitchIR;
extern lv_obj_t * uic_LabelIR;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

