// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENPIN_H
#define UI_SCREENPIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPin
extern void ui_ScreenPin_screen_init(void);
extern void ui_ScreenPin_screen_destroy(void);
extern lv_obj_t * ui_ScreenPin;
extern lv_obj_t * ui_ContainerPin;
extern lv_obj_t * ui_topBar2;
extern lv_obj_t * ui_PanelNumber2;
extern lv_obj_t * ui_ContainerPinUser;
extern lv_obj_t * ui_LabelPinUser;
extern void ui_event_TextAreaPinUser(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPinUser;
extern lv_obj_t * ui_ContainerPinAdvanced;
extern lv_obj_t * ui_LabelPinAdvanced;
extern void ui_event_TextAreaPinAdvanced(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPinAdvanced;
extern lv_obj_t * ui_PanelBackPin;
extern void ui_event_ButtonBackPin(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackPin;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenAdvance;
extern lv_obj_t * uic_ContainerPin;
extern lv_obj_t * uic_ContainerPinUser;
extern lv_obj_t * uic_LabelPinUser;
extern lv_obj_t * uic_TextAreaPinUser;
extern lv_obj_t * uic_ContainerPinAdvanced;
extern lv_obj_t * uic_LabelPinAdvanced;
extern lv_obj_t * uic_TextAreaPinAdvanced;
extern lv_obj_t * uic_PanelBackPin;
extern lv_obj_t * uic_ButtonBackPin;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

