// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENMODES_H
#define UI_SCREENMODES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenModes
extern void ui_ScreenModes_screen_init(void);
extern void ui_ScreenModes_screen_destroy(void);
extern lv_obj_t * ui_ScreenModes;
extern lv_obj_t * ui_ContainerModes;
extern lv_obj_t * ui_topBar4;
extern void ui_event_RollerModes(lv_event_t * e);
extern lv_obj_t * ui_RollerModes;
extern void ui_event_SliderModesFan_Slider1(lv_event_t * e);
extern lv_obj_t * ui_SliderModesFan;
extern void ui_event_SliderModesLed_Slider1(lv_event_t * e);
extern lv_obj_t * ui_SliderModesLed;
extern void ui_event_SliderModesPrivate(lv_event_t * e);
extern lv_obj_t * ui_SliderModesPrivate;
extern lv_obj_t * ui_LabelOn2;
extern lv_obj_t * ui_LabelOff2;
extern lv_obj_t * ui_PanelBackModes;
extern void ui_event_ButtonBackModes(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackModes;
extern lv_obj_t * ui_PanelFan2;
extern lv_obj_t * ui_PanelLed2;
extern lv_obj_t * ui_PanelPrivate2;
extern lv_obj_t * ui_PanelSaveModes;
extern void ui_event_ButtonSaveModes(lv_event_t * e);
extern lv_obj_t * ui_ButtonSaveModes;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenModes;
extern lv_obj_t * uic_ContainerModes;
extern lv_obj_t * uic_RollerModes;
extern lv_obj_t * uic_SliderModesFan;
extern lv_obj_t * uic_SliderModesLed;
extern lv_obj_t * uic_SliderModesPrivate;
extern lv_obj_t * uic_PanelBackModes;
extern lv_obj_t * uic_ButtonBackModes;
extern lv_obj_t * uic_PanelSaveModes;
extern lv_obj_t * uic_ButtonSaveModes;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

