// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_topBar;
extern void ui_event_ButtonPhone(lv_event_t * e);
extern lv_obj_t * ui_ButtonPhone;
extern void ui_event_ButtonWork(lv_event_t * e);
extern lv_obj_t * ui_ButtonWork;
extern void ui_event_ButtonRelax(lv_event_t * e);
extern lv_obj_t * ui_ButtonRelax;
extern void ui_event_SliderFan_Slider1(lv_event_t * e);
extern lv_obj_t * ui_SliderFan;
extern lv_obj_t * ui_PanelFan;
extern void ui_event_SliderLed_Slider1(lv_event_t * e);
extern lv_obj_t * ui_SliderLed;
extern lv_obj_t * ui_PanelLed;
extern void ui_event_SliderPrivate(lv_event_t * e);
extern lv_obj_t * ui_SliderPrivate;
extern lv_obj_t * ui_LabelPrivateOn;
extern lv_obj_t * ui_LabelPrivateOff;
extern lv_obj_t * ui_PanelPrivate;
extern void ui_event_SliderLock(lv_event_t * e);
extern lv_obj_t * ui_SliderLock;
extern lv_obj_t * ui_LabelLockOn;
extern lv_obj_t * ui_LabelLockOff;
extern lv_obj_t * ui_PanelLock;
extern void ui_event_ButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_ButtonSettings;
extern lv_obj_t * ui_PanelButtons;
extern void ui_event_ButtonClean(lv_event_t * e);
extern lv_obj_t * ui_ButtonClean;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenMain;
extern lv_obj_t * uic_topBar;
extern lv_obj_t * uic_ButtonPhone;
extern lv_obj_t * uic_ButtonRelax;
extern lv_obj_t * uic_PanelFan;
extern lv_obj_t * uic_SliderLed;
extern lv_obj_t * uic_PanelLed;
extern lv_obj_t * uic_SliderPrivate;
extern lv_obj_t * uic_LabelPrivateOn;
extern lv_obj_t * uic_LabelPrivateOff;
extern lv_obj_t * uic_PanelPrivate;
extern lv_obj_t * uic_SliderLock;
extern lv_obj_t * uic_LabelLockOn;
extern lv_obj_t * uic_LabelLockOff;
extern lv_obj_t * uic_PanelLock;
extern lv_obj_t * uic_ButtonSettings;
extern lv_obj_t * uic_PanelButtons;
extern lv_obj_t * uic_ButtonClean;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

