// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_ImageLogo;
lv_obj_t * uic_ContainerLogo;
lv_obj_t * uic_ScreenLogo;
lv_obj_t * ui_ScreenLogo = NULL;
lv_obj_t * ui_ContainerLogo = NULL;
lv_obj_t * ui_ImageLogo = NULL;
// event funtions

// build funtions

void ui_ScreenLogo_screen_init(void)
{
    ui_ScreenLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLogo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_ScreenLogo, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLogo, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ContainerLogo = lv_obj_create(ui_ScreenLogo);
    lv_obj_remove_style_all(ui_ContainerLogo);
    lv_obj_set_width(ui_ContainerLogo, lv_pct(100));
    lv_obj_set_height(ui_ContainerLogo, lv_pct(100));
    lv_obj_set_align(ui_ContainerLogo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerLogo, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerLogo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLogo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ImageLogo = lv_img_create(ui_ContainerLogo);
    lv_img_set_src(ui_ImageLogo, &ui_img_1615156922);
    lv_obj_set_width(ui_ImageLogo, LV_SIZE_CONTENT);   /// 501
    lv_obj_set_height(ui_ImageLogo, LV_SIZE_CONTENT);    /// 175
    lv_obj_set_x(ui_ImageLogo, 197);
    lv_obj_set_y(ui_ImageLogo, 79);
    lv_obj_set_align(ui_ImageLogo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImageLogo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_opa(ui_ImageLogo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ScreenLogo = ui_ScreenLogo;
    uic_ContainerLogo = ui_ContainerLogo;
    uic_ImageLogo = ui_ImageLogo;

}

void ui_ScreenLogo_screen_destroy(void)
{
    if(ui_ScreenLogo) lv_obj_del(ui_ScreenLogo);

    // NULL screen variables
    uic_ScreenLogo = NULL;
    ui_ScreenLogo = NULL;
    uic_ContainerLogo = NULL;
    ui_ContainerLogo = NULL;
    uic_ImageLogo = NULL;
    ui_ImageLogo = NULL;

}
