// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENADVANCED_H
#define UI_SCREENADVANCED_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAdvanced
extern void ui_ScreenAdvanced_screen_init(void);
extern void ui_ScreenAdvanced_screen_destroy(void);
extern lv_obj_t * ui_ScreenAdvanced;
extern lv_obj_t * ui_PanelPin;
extern lv_obj_t * ui_LabelPin;
extern void ui_event_ButtonPin(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin;
extern lv_obj_t * ui_topBar3;
extern lv_obj_t * ui_PanelControl;
extern lv_obj_t * ui_LabelControl;
extern void ui_event_ButtonControl(lv_event_t * e);
extern lv_obj_t * ui_ButtonControl;
extern lv_obj_t * ui_PanelInfo;
extern lv_obj_t * ui_LabelInfo;
extern void ui_event_ButtonInfo(lv_event_t * e);
extern lv_obj_t * ui_ButtonInfo;
extern lv_obj_t * ui_PanelBackAdvanced;
extern void ui_event_ButtonBackAdvanced(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackAdvanced;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenAdvanced;
extern lv_obj_t * uic_PanelPin;
extern lv_obj_t * uic_LabelPin;
extern lv_obj_t * uic_ButtonPin;
extern lv_obj_t * uic_PanelControl;
extern lv_obj_t * uic_LabelControl;
extern lv_obj_t * uic_ButtonControl;
extern lv_obj_t * uic_PanelInfo;
extern lv_obj_t * uic_LabelInfo;
extern lv_obj_t * uic_ButtonInfo;
extern lv_obj_t * uic_PanelBackAdvanced;
extern lv_obj_t * uic_ButtonBackAdvanced;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

