// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_ButtonBackAdvanced;
lv_obj_t * uic_PanelBackAdvanced;
lv_obj_t * uic_ButtonInfo;
lv_obj_t * uic_LabelInfo;
lv_obj_t * uic_PanelInfo;
lv_obj_t * uic_ButtonControl;
lv_obj_t * uic_LabelControl;
lv_obj_t * uic_PanelControl;
lv_obj_t * uic_ButtonPin;
lv_obj_t * uic_LabelPin;
lv_obj_t * uic_PanelPin;
lv_obj_t * uic_ContainerAdvanced;
lv_obj_t * uic_ScreenAdvanced;
lv_obj_t * ui_ScreenAdvanced = NULL;
lv_obj_t * ui_ContainerAdvanced = NULL;
lv_obj_t * ui_PanelPin = NULL;
lv_obj_t * ui_LabelPin = NULL;
lv_obj_t * ui_ButtonPin = NULL;
lv_obj_t * ui_topBar3 = NULL;
lv_obj_t * ui_PanelControl = NULL;
lv_obj_t * ui_LabelControl = NULL;
lv_obj_t * ui_ButtonControl = NULL;
lv_obj_t * ui_PanelInfo = NULL;
lv_obj_t * ui_LabelInfo = NULL;
lv_obj_t * ui_ButtonInfo = NULL;
lv_obj_t * ui_PanelBackAdvanced = NULL;
lv_obj_t * ui_ButtonBackAdvanced = NULL;
// event funtions
void ui_event_ButtonPin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonPin_Clicked(e);
        _ui_screen_change(&ui_ScreenPin, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenPin_screen_init);
    }
}

void ui_event_ButtonControl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonTimer_Clicked(e);
        _ui_screen_change(&ui_ScreenControl, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenControl_screen_init);
    }
}

void ui_event_ButtonInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonInfo_Clicked(e);
        _ui_screen_change(&ui_ScreenInfo, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenInfo_screen_init);
    }
}

void ui_event_ButtonBackAdvanced(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonBackAdvanced_Clicked(e);
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
    }
}

// build funtions

void ui_ScreenAdvanced_screen_init(void)
{
    ui_ScreenAdvanced = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAdvanced, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerAdvanced = lv_obj_create(ui_ScreenAdvanced);
    lv_obj_remove_style_all(ui_ContainerAdvanced);
    lv_obj_set_width(ui_ContainerAdvanced, lv_pct(100));
    lv_obj_set_height(ui_ContainerAdvanced, lv_pct(100));
    lv_obj_set_align(ui_ContainerAdvanced, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerAdvanced, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerAdvanced, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerAdvanced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPin = lv_obj_create(ui_ContainerAdvanced);
    lv_obj_set_width(ui_PanelPin, 150);
    lv_obj_set_height(ui_PanelPin, 150);
    lv_obj_set_x(ui_PanelPin, -200);
    lv_obj_set_y(ui_PanelPin, 210);
    lv_obj_set_align(ui_PanelPin, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelPin, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_PanelPin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPin, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPin = lv_label_create(ui_PanelPin);
    lv_obj_set_width(ui_LabelPin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPin, 0);
    lv_obj_set_y(ui_LabelPin, 10);
    lv_obj_set_align(ui_LabelPin, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelPin, "PIN");
    lv_obj_add_flag(ui_LabelPin, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    ui_object_set_themeable_style_property(ui_LabelPin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_LabelPin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_font(ui_LabelPin, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPin = lv_btn_create(ui_PanelPin);
    lv_obj_set_width(ui_ButtonPin, 90);
    lv_obj_set_height(ui_ButtonPin, 90);
    lv_obj_set_x(ui_ButtonPin, 0);
    lv_obj_set_y(ui_ButtonPin, -10);
    lv_obj_set_align(ui_ButtonPin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPin, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPin, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonPin, &ui_img_pin_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonPin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonPin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar3 = ui_topBar_create(ui_ContainerAdvanced);
    lv_obj_set_x(ui_topBar3, 0);
    lv_obj_set_y(ui_topBar3, 20);

    lv_label_set_text(ui_comp_get_child(ui_topBar3, UI_COMP_TOPBAR_LABELMENU), "Advanced");

    ui_PanelControl = lv_obj_create(ui_ContainerAdvanced);
    lv_obj_set_width(ui_PanelControl, 150);
    lv_obj_set_height(ui_PanelControl, 150);
    lv_obj_set_x(ui_PanelControl, 0);
    lv_obj_set_y(ui_PanelControl, 210);
    lv_obj_set_align(ui_PanelControl, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelControl, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_PanelControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelControl, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelControl = lv_label_create(ui_PanelControl);
    lv_obj_set_width(ui_LabelControl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelControl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelControl, 0);
    lv_obj_set_y(ui_LabelControl, 10);
    lv_obj_set_align(ui_LabelControl, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelControl, "Control");
    lv_obj_add_flag(ui_LabelControl, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    ui_object_set_themeable_style_property(ui_LabelControl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_LabelControl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_font(ui_LabelControl, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonControl = lv_btn_create(ui_PanelControl);
    lv_obj_set_width(ui_ButtonControl, 90);
    lv_obj_set_height(ui_ButtonControl, 90);
    lv_obj_set_x(ui_ButtonControl, 0);
    lv_obj_set_y(ui_ButtonControl, -10);
    lv_obj_set_align(ui_ButtonControl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonControl, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonControl, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonControl, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonControl, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonControl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonControl, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);

    ui_PanelInfo = lv_obj_create(ui_ContainerAdvanced);
    lv_obj_set_width(ui_PanelInfo, 150);
    lv_obj_set_height(ui_PanelInfo, 150);
    lv_obj_set_x(ui_PanelInfo, 200);
    lv_obj_set_y(ui_PanelInfo, 210);
    lv_obj_set_align(ui_PanelInfo, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelInfo, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_PanelInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelInfo, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInfo = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_LabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInfo, 0);
    lv_obj_set_y(ui_LabelInfo, 10);
    lv_obj_set_align(ui_LabelInfo, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelInfo, "Info");
    lv_obj_add_flag(ui_LabelInfo, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    ui_object_set_themeable_style_property(ui_LabelInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_LabelInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_font(ui_LabelInfo, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonInfo = lv_btn_create(ui_PanelInfo);
    lv_obj_set_width(ui_ButtonInfo, 90);
    lv_obj_set_height(ui_ButtonInfo, 90);
    lv_obj_set_x(ui_ButtonInfo, 0);
    lv_obj_set_y(ui_ButtonInfo, -10);
    lv_obj_set_align(ui_ButtonInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInfo, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonInfo, &ui_img_info_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);

    ui_PanelBackAdvanced = lv_obj_create(ui_ContainerAdvanced);
    lv_obj_set_width(ui_PanelBackAdvanced, 50);
    lv_obj_set_height(ui_PanelBackAdvanced, 50);
    lv_obj_set_x(ui_PanelBackAdvanced, 50);
    lv_obj_set_y(ui_PanelBackAdvanced, 50);
    lv_obj_clear_flag(ui_PanelBackAdvanced, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBackAdvanced, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBackAdvanced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBackAdvanced, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBackAdvanced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackAdvanced = lv_btn_create(ui_PanelBackAdvanced);
    lv_obj_set_width(ui_ButtonBackAdvanced, 100);
    lv_obj_set_height(ui_ButtonBackAdvanced, 50);
    lv_obj_set_align(ui_ButtonBackAdvanced, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBackAdvanced, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBackAdvanced, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackAdvanced, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackAdvanced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBackAdvanced, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonBackAdvanced, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonBackAdvanced, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_border_color(ui_ButtonBackAdvanced, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonBackAdvanced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonPin, ui_event_ButtonPin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonControl, ui_event_ButtonControl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonInfo, ui_event_ButtonInfo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBackAdvanced, ui_event_ButtonBackAdvanced, LV_EVENT_ALL, NULL);
    uic_ScreenAdvanced = ui_ScreenAdvanced;
    uic_ContainerAdvanced = ui_ContainerAdvanced;
    uic_PanelPin = ui_PanelPin;
    uic_LabelPin = ui_LabelPin;
    uic_ButtonPin = ui_ButtonPin;
    uic_PanelControl = ui_PanelControl;
    uic_LabelControl = ui_LabelControl;
    uic_ButtonControl = ui_ButtonControl;
    uic_PanelInfo = ui_PanelInfo;
    uic_LabelInfo = ui_LabelInfo;
    uic_ButtonInfo = ui_ButtonInfo;
    uic_PanelBackAdvanced = ui_PanelBackAdvanced;
    uic_ButtonBackAdvanced = ui_ButtonBackAdvanced;

}

void ui_ScreenAdvanced_screen_destroy(void)
{
    if(ui_ScreenAdvanced) lv_obj_del(ui_ScreenAdvanced);

    // NULL screen variables
    uic_ScreenAdvanced = NULL;
    ui_ScreenAdvanced = NULL;
    uic_ContainerAdvanced = NULL;
    ui_ContainerAdvanced = NULL;
    uic_PanelPin = NULL;
    ui_PanelPin = NULL;
    uic_LabelPin = NULL;
    ui_LabelPin = NULL;
    uic_ButtonPin = NULL;
    ui_ButtonPin = NULL;
    ui_topBar3 = NULL;
    uic_PanelControl = NULL;
    ui_PanelControl = NULL;
    uic_LabelControl = NULL;
    ui_LabelControl = NULL;
    uic_ButtonControl = NULL;
    ui_ButtonControl = NULL;
    uic_PanelInfo = NULL;
    ui_PanelInfo = NULL;
    uic_LabelInfo = NULL;
    ui_LabelInfo = NULL;
    uic_ButtonInfo = NULL;
    ui_ButtonInfo = NULL;
    uic_PanelBackAdvanced = NULL;
    ui_PanelBackAdvanced = NULL;
    uic_ButtonBackAdvanced = NULL;
    ui_ButtonBackAdvanced = NULL;

}
