// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_Label1SaveTimer;
lv_obj_t * uic_ButtonSaveTimer;
lv_obj_t * uic_PanelSaveTimer;
lv_obj_t * uic_ButtonBackTimer;
lv_obj_t * uic_PanelBackTimer;
lv_obj_t * uic_PanelTLed;
lv_obj_t * uic_PanelTFan;
lv_obj_t * uic_RollerLed;
lv_obj_t * uic_RollerFan;
lv_obj_t * uic_topBarTimer;
lv_obj_t * uic_ScreenTimer;
lv_obj_t * ui_ScreenTimer = NULL;
lv_obj_t * ui_topBarTimer = NULL;
lv_obj_t * ui_RollerFan = NULL;
lv_obj_t * ui_RollerLed = NULL;
lv_obj_t * ui_PanelTFan = NULL;
lv_obj_t * ui_PanelTLed = NULL;
lv_obj_t * ui_PanelBackTimer = NULL;
lv_obj_t * ui_ButtonBackTimer = NULL;
lv_obj_t * ui_PanelSaveTimer = NULL;
lv_obj_t * ui_ButtonSaveTimer = NULL;
lv_obj_t * ui_Label1SaveTimer = NULL;
// event funtions
void ui_event_RollerFan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        ui_event_RollerFanTimer_Ready(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_RollerFanTimer_Change(e);
    }
}

void ui_event_RollerLed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        ui_event_RollerLedTimer_Ready(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_RollerLedTimer_Change(e);
    }
}

void ui_event_ButtonBackTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonBackTimer_Clicked(e);
        _ui_screen_change(&ui_ScreenOption, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenOption_screen_init);
    }
}

void ui_event_ButtonSaveTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonSaveTimer_clicked(e);
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
    }
}

// build funtions

void ui_ScreenTimer_screen_init(void)
{
    ui_ScreenTimer = lv_obj_create(NULL);
    lv_obj_set_style_bg_img_src(ui_ScreenTimer, &img_base_azul, 0);
    lv_obj_set_style_bg_img_opa(ui_ScreenTimer, LV_OPA_COVER, 0);
    lv_obj_clear_flag(ui_ScreenTimer, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_topBarTimer = ui_topBar_create(ui_ScreenTimer);
    lv_obj_set_x(ui_topBarTimer, 0);
    lv_obj_set_y(ui_topBarTimer, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBarTimer, UI_COMP_TOPBAR_LABELMENU), "Timer");

    ui_RollerFan = lv_roller_create(ui_ScreenTimer);
    lv_roller_set_options(ui_RollerFan, "30 seg\n1 min\n3 min\n5 min\n10 min", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerFan, 150);
    lv_obj_set_height(ui_RollerFan, 150);
    lv_obj_set_x(ui_RollerFan, -100);
    lv_obj_set_y(ui_RollerFan, 300);
    lv_obj_set_align(ui_RollerFan, LV_ALIGN_TOP_MID);
    /* Fondo del roller tipo glass */
    lv_obj_set_style_bg_color(ui_RollerFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerFan, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerFan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerFan, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RollerFan, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Texto normal */
    lv_obj_set_style_text_color(ui_RollerFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerFan, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Texto seleccionado */
    lv_obj_set_style_text_color(ui_RollerFan, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerFan, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    /* Fondo seleccionado moderno */
    lv_obj_set_style_bg_color(ui_RollerFan, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerFan, 40, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RollerFan, 15, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_RollerLed = lv_roller_create(ui_ScreenTimer);
    lv_roller_set_options(ui_RollerLed, "30 seg\n1 min\n3 min\n5 min\n10 min", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerLed, 150);
    lv_obj_set_height(ui_RollerLed, 150);
    lv_obj_set_x(ui_RollerLed, 100);
    lv_obj_set_y(ui_RollerLed, 300);
    lv_obj_set_align(ui_RollerLed, LV_ALIGN_TOP_MID);
    /* Fondo del roller tipo glass */
    lv_obj_set_style_bg_color(ui_RollerLed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerLed, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerLed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerLed, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerLed, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RollerLed, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Texto normal */
    lv_obj_set_style_text_color(ui_RollerLed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerLed, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Texto seleccionado */
    lv_obj_set_style_text_color(ui_RollerLed, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerLed, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);

    /* Fondo seleccionado moderno */
    lv_obj_set_style_bg_color(ui_RollerLed, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerLed, 40, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RollerLed, 15, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PanelTFan = lv_obj_create(ui_ScreenTimer);
    lv_obj_set_width(ui_PanelTFan, 90);
    lv_obj_set_height(ui_PanelTFan, 80);
    lv_obj_set_x(ui_PanelTFan, -100);
    lv_obj_set_y(ui_PanelTFan, -100);
    lv_obj_set_align(ui_PanelTFan, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTFan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTFan, &ui_img_timer_fan_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_PanelTFan, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_PanelTFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTFan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTLed = lv_obj_create(ui_ScreenTimer);
    lv_obj_set_width(ui_PanelTLed, 90);
    lv_obj_set_height(ui_PanelTLed, 80);
    lv_obj_set_x(ui_PanelTLed, 100);
    lv_obj_set_y(ui_PanelTLed, -100);
    lv_obj_set_align(ui_PanelTLed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTLed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTLed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTLed, &ui_img_timer_led_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_PanelTLed, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_PanelTLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTLed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTLed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBackTimer = lv_obj_create(ui_ScreenTimer);
    lv_obj_set_width(ui_PanelBackTimer, 80);
    lv_obj_set_height(ui_PanelBackTimer, 80);
    lv_obj_set_x(ui_PanelBackTimer, 50);
    lv_obj_set_y(ui_PanelBackTimer, 50);
    lv_obj_clear_flag(ui_PanelBackTimer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBackTimer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBackTimer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBackTimer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBackTimer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackTimer = lv_btn_create(ui_PanelBackTimer);
    lv_obj_set_width(ui_ButtonBackTimer, 80);
    lv_obj_set_height(ui_ButtonBackTimer, 80);
    lv_obj_set_align(ui_ButtonBackTimer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBackTimer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBackTimer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackTimer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackTimer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBackTimer, &img_back_br, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonBackTimer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonBackTimer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_border_color(ui_ButtonBackTimer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonBackTimer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSaveTimer = lv_btn_create(ui_ScreenTimer);
    lv_obj_set_width(ui_ButtonSaveTimer, 141);
    lv_obj_set_height(ui_ButtonSaveTimer, 64);
    lv_obj_set_x(ui_ButtonSaveTimer, -100);
    lv_obj_set_y(ui_ButtonSaveTimer, -50);
    lv_obj_set_align(ui_ButtonSaveTimer, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_ButtonSaveTimer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /* === Estilo igual al botón original === */
    lv_obj_set_style_bg_color(ui_ButtonSaveTimer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonSaveTimer, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSaveTimer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1SaveTimer = lv_label_create(ui_ButtonSaveTimer);
    lv_obj_set_width(ui_Label1SaveTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1SaveTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1SaveTimer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1SaveTimer, "Save");
    lv_obj_set_style_text_color(ui_Label1SaveTimer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1SaveTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1SaveTimer, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RollerFan, ui_event_RollerFan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerLed, ui_event_RollerLed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBackTimer, ui_event_ButtonBackTimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSaveTimer, ui_event_ButtonSaveTimer, LV_EVENT_ALL, NULL);
    uic_ScreenTimer = ui_ScreenTimer;
    uic_topBarTimer = ui_topBarTimer;
    uic_RollerFan = ui_RollerFan;
    uic_RollerLed = ui_RollerLed;
    uic_PanelTFan = ui_PanelTFan;
    uic_PanelTLed = ui_PanelTLed;
    uic_PanelBackTimer = ui_PanelBackTimer;
    uic_ButtonBackTimer = ui_ButtonBackTimer;
    uic_PanelSaveTimer = ui_PanelSaveTimer;
    uic_ButtonSaveTimer = ui_ButtonSaveTimer;
    uic_Label1SaveTimer = ui_Label1SaveTimer;

}

void ui_ScreenTimer_screen_destroy(void)
{
    if(ui_ScreenTimer) lv_obj_del(ui_ScreenTimer);

    // NULL screen variables
    uic_ScreenTimer = NULL;
    ui_ScreenTimer = NULL;
    uic_topBarTimer = NULL;
    ui_topBarTimer = NULL;
    uic_RollerFan = NULL;
    ui_RollerFan = NULL;
    uic_RollerLed = NULL;
    ui_RollerLed = NULL;
    uic_PanelTFan = NULL;
    ui_PanelTFan = NULL;
    uic_PanelTLed = NULL;
    ui_PanelTLed = NULL;
    uic_PanelBackTimer = NULL;
    ui_PanelBackTimer = NULL;
    uic_ButtonBackTimer = NULL;
    ui_ButtonBackTimer = NULL;
    uic_PanelSaveTimer = NULL;
    ui_PanelSaveTimer = NULL;
    uic_ButtonSaveTimer = NULL;
    ui_ButtonSaveTimer = NULL;
    uic_Label1SaveTimer = NULL;
    ui_Label1SaveTimer = NULL;

}
