// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_ButtonBackOption;
lv_obj_t * uic_PanelBackOption;
lv_obj_t * uic_ButtonModes;
lv_obj_t * uic_LabelModes;
lv_obj_t * uic_PanelModes;
lv_obj_t * uic_ButtonDate;
lv_obj_t * uic_LabelDate;
lv_obj_t * uic_PanelDate;
lv_obj_t * uic_ButtonTimer;
lv_obj_t * uic_LabelTimer;
lv_obj_t * uic_PanelTimer;
lv_obj_t * uic_ContainerOption;
lv_obj_t * uic_ScreenOption;
lv_obj_t * ui_ScreenOption = NULL;
lv_obj_t * ui_ContainerOption = NULL;
lv_obj_t * ui_topBar1 = NULL;
lv_obj_t * ui_PanelTimer = NULL;
lv_obj_t * ui_LabelTimer = NULL;
lv_obj_t * ui_ButtonTimer = NULL;
lv_obj_t * ui_PanelDate = NULL;
lv_obj_t * ui_LabelDate = NULL;
lv_obj_t * ui_ButtonDate = NULL;
lv_obj_t * ui_PanelModes = NULL;
lv_obj_t * ui_LabelModes = NULL;
lv_obj_t * ui_ButtonModes = NULL;
lv_obj_t * ui_PanelBackOption = NULL;
lv_obj_t * ui_ButtonBackOption = NULL;
// event funtions
void ui_event_ButtonTimer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonTimer_Clicked(e);
        _ui_screen_change(&ui_ScreenTimer, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenTimer_screen_init);
    }
}

void ui_event_ButtonDate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonDate_Clicked(e);
        _ui_screen_change(&ui_ScreenDate, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenDate_screen_init);
    }
}

void ui_event_ButtonModes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonModes_Clicked(e);
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
    }
}

void ui_event_ButtonBackOption(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonBackOption_Clicked(e);
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
    }
}

// build funtions

void ui_ScreenOption_screen_init(void)
{
    ui_ScreenOption = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenOption, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ContainerOption = lv_obj_create(ui_ScreenOption);
    lv_obj_remove_style_all(ui_ContainerOption);
    lv_obj_set_width(ui_ContainerOption, lv_pct(100));
    lv_obj_set_height(ui_ContainerOption, lv_pct(100));
    lv_obj_set_align(ui_ContainerOption, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerOption,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_ContainerOption, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerOption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar1 = ui_topBar_create(ui_ContainerOption);
    lv_obj_set_x(ui_topBar1, 0);
    lv_obj_set_y(ui_topBar1, 0);

    lv_label_set_text(ui_comp_get_child(ui_topBar1, UI_COMP_TOPBAR_LABELMENU), "Option");

    ui_PanelTimer = lv_obj_create(ui_ContainerOption);
    lv_obj_set_width(ui_PanelTimer, 150);
    lv_obj_set_height(ui_PanelTimer, 150);
    lv_obj_set_x(ui_PanelTimer, -200);
    lv_obj_set_y(ui_PanelTimer, 210);
    lv_obj_set_align(ui_PanelTimer, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelTimer, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_PanelTimer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTimer, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimer = lv_label_create(ui_PanelTimer);
    lv_obj_set_width(ui_LabelTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimer, 0);
    lv_obj_set_y(ui_LabelTimer, 10);
    lv_obj_set_align(ui_LabelTimer, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelTimer, "Timer");
    lv_obj_add_flag(ui_LabelTimer, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    ui_object_set_themeable_style_property(ui_LabelTimer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_LabelTimer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_font(ui_LabelTimer, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTimer = lv_btn_create(ui_PanelTimer);
    lv_obj_set_width(ui_ButtonTimer, 90);
    lv_obj_set_height(ui_ButtonTimer, 90);
    lv_obj_set_x(ui_ButtonTimer, 0);
    lv_obj_set_y(ui_ButtonTimer, -10);
    lv_obj_set_align(ui_ButtonTimer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTimer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTimer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonTimer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTimer, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonTimer, &ui_img_timer_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ButtonTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonTimer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonTimer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);

    ui_PanelDate = lv_obj_create(ui_ContainerOption);
    lv_obj_set_width(ui_PanelDate, 150);
    lv_obj_set_height(ui_PanelDate, 150);
    lv_obj_set_x(ui_PanelDate, 0);
    lv_obj_set_y(ui_PanelDate, 210);
    lv_obj_set_align(ui_PanelDate, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelDate, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_PanelDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelDate, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate = lv_label_create(ui_PanelDate);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, 0);
    lv_obj_set_y(ui_LabelDate, 10);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelDate, "Date");
    lv_obj_add_flag(ui_LabelDate, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    ui_object_set_themeable_style_property(ui_LabelDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_LabelDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_font(ui_LabelDate, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDate = lv_btn_create(ui_PanelDate);
    lv_obj_set_width(ui_ButtonDate, 90);
    lv_obj_set_height(ui_ButtonDate, 90);
    lv_obj_set_x(ui_ButtonDate, 0);
    lv_obj_set_y(ui_ButtonDate, -10);
    lv_obj_set_align(ui_ButtonDate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonDate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDate, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonDate, &ui_img_data_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);

    ui_PanelModes = lv_obj_create(ui_ContainerOption);
    lv_obj_set_width(ui_PanelModes, 150);
    lv_obj_set_height(ui_PanelModes, 150);
    lv_obj_set_x(ui_PanelModes, 204);
    lv_obj_set_y(ui_PanelModes, 210);
    lv_obj_set_align(ui_PanelModes, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelModes, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_PanelModes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelModes, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelModes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelModes = lv_label_create(ui_PanelModes);
    lv_obj_set_width(ui_LabelModes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModes, 0);
    lv_obj_set_y(ui_LabelModes, 10);
    lv_obj_set_align(ui_LabelModes, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelModes, "Modes");
    lv_obj_add_flag(ui_LabelModes, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    ui_object_set_themeable_style_property(ui_LabelModes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_LabelModes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_text_font(ui_LabelModes, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonModes = lv_btn_create(ui_PanelModes);
    lv_obj_set_width(ui_ButtonModes, 80);
    lv_obj_set_height(ui_ButtonModes, 80);
    lv_obj_set_x(ui_ButtonModes, 3);
    lv_obj_set_y(ui_ButtonModes, -4);
    lv_obj_set_align(ui_ButtonModes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonModes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonModes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonModes, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonModes, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonModes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonModes, &ui_img_control_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonModes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonModes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);

    ui_PanelBackOption = lv_obj_create(ui_ContainerOption);
    lv_obj_set_width(ui_PanelBackOption, 50);
    lv_obj_set_height(ui_PanelBackOption, 50);
    lv_obj_set_x(ui_PanelBackOption, 50);
    lv_obj_set_y(ui_PanelBackOption, 50);
    lv_obj_clear_flag(ui_PanelBackOption, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBackOption, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBackOption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBackOption, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBackOption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackOption = lv_btn_create(ui_PanelBackOption);
    lv_obj_set_width(ui_ButtonBackOption, 100);
    lv_obj_set_height(ui_ButtonBackOption, 50);
    lv_obj_set_align(ui_ButtonBackOption, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBackOption, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBackOption, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackOption, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackOption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBackOption, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonBackOption, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonBackOption, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_border_color(ui_ButtonBackOption, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonBackOption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonTimer, ui_event_ButtonTimer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonDate, ui_event_ButtonDate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonModes, ui_event_ButtonModes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBackOption, ui_event_ButtonBackOption, LV_EVENT_ALL, NULL);
    uic_ScreenOption = ui_ScreenOption;
    uic_ContainerOption = ui_ContainerOption;
    uic_PanelTimer = ui_PanelTimer;
    uic_LabelTimer = ui_LabelTimer;
    uic_ButtonTimer = ui_ButtonTimer;
    uic_PanelDate = ui_PanelDate;
    uic_LabelDate = ui_LabelDate;
    uic_ButtonDate = ui_ButtonDate;
    uic_PanelModes = ui_PanelModes;
    uic_LabelModes = ui_LabelModes;
    uic_ButtonModes = ui_ButtonModes;
    uic_PanelBackOption = ui_PanelBackOption;
    uic_ButtonBackOption = ui_ButtonBackOption;

}

void ui_ScreenOption_screen_destroy(void)
{
    if(ui_ScreenOption) lv_obj_del(ui_ScreenOption);

    // NULL screen variables
    uic_ScreenOption = NULL;
    ui_ScreenOption = NULL;
    uic_ContainerOption = NULL;
    ui_ContainerOption = NULL;
    ui_topBar1 = NULL;
    uic_PanelTimer = NULL;
    ui_PanelTimer = NULL;
    uic_LabelTimer = NULL;
    ui_LabelTimer = NULL;
    uic_ButtonTimer = NULL;
    ui_ButtonTimer = NULL;
    uic_PanelDate = NULL;
    ui_PanelDate = NULL;
    uic_LabelDate = NULL;
    ui_LabelDate = NULL;
    uic_ButtonDate = NULL;
    ui_ButtonDate = NULL;
    uic_PanelModes = NULL;
    ui_PanelModes = NULL;
    uic_LabelModes = NULL;
    ui_LabelModes = NULL;
    uic_ButtonModes = NULL;
    ui_ButtonModes = NULL;
    uic_PanelBackOption = NULL;
    ui_PanelBackOption = NULL;
    uic_ButtonBackOption = NULL;
    ui_ButtonBackOption = NULL;

}
