// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#include "../ui.h"

lv_obj_t * uic_ButtonBackInfo;
lv_obj_t * uic_PanelBackInfo;
lv_obj_t * uic_ContainerInfo;
lv_obj_t * uic_ScreenInfo;
lv_obj_t * ui_ScreenInfo = NULL;
lv_obj_t * ui_ContainerInfo = NULL;
lv_obj_t * ui_PanelBackInfo = NULL;
lv_obj_t * ui_ButtonBackInfo = NULL;
lv_obj_t * ui_topBar5 = NULL;
// event funtions
void ui_event_ButtonBackInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_ButtonBackInfo_Clicked(e);
        _ui_screen_change(&ui_ScreenAdvanced, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenAdvanced_screen_init);
    }
}

// build funtions

void ui_ScreenInfo_screen_init(void)
{
    ui_ScreenInfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerInfo = lv_obj_create(ui_ScreenInfo);
    lv_obj_remove_style_all(ui_ContainerInfo);
    lv_obj_set_width(ui_ContainerInfo, 1024);
    lv_obj_set_height(ui_ContainerInfo, 600);
    lv_obj_set_align(ui_ContainerInfo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBackInfo = lv_obj_create(ui_ContainerInfo);
    lv_obj_set_width(ui_PanelBackInfo, 50);
    lv_obj_set_height(ui_PanelBackInfo, 50);
    lv_obj_set_x(ui_PanelBackInfo, 50);
    lv_obj_set_y(ui_PanelBackInfo, 50);
    lv_obj_clear_flag(ui_PanelBackInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBackInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBackInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBackInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBackInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBackInfo = lv_btn_create(ui_PanelBackInfo);
    lv_obj_set_width(ui_ButtonBackInfo, 100);
    lv_obj_set_height(ui_ButtonBackInfo, 50);
    lv_obj_set_align(ui_ButtonBackInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBackInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBackInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonBackInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBackInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBackInfo, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ButtonBackInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_IndicatorOn);
    ui_object_set_themeable_style_property(ui_ButtonBackInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_IndicatorOn);
    lv_obj_set_style_border_color(ui_ButtonBackInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonBackInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar5 = ui_topBar_create(ui_ScreenInfo);
    lv_obj_set_x(ui_topBar5, 0);
    lv_obj_set_y(ui_topBar5, 20);

    lv_label_set_text(ui_comp_get_child(ui_topBar5, UI_COMP_TOPBAR_LABELMENU), "Information");

    lv_obj_add_event_cb(ui_ButtonBackInfo, ui_event_ButtonBackInfo, LV_EVENT_ALL, NULL);
    uic_ScreenInfo = ui_ScreenInfo;
    uic_ContainerInfo = ui_ContainerInfo;
    uic_PanelBackInfo = ui_PanelBackInfo;
    uic_ButtonBackInfo = ui_ButtonBackInfo;

}

void ui_ScreenInfo_screen_destroy(void)
{
    if(ui_ScreenInfo) lv_obj_del(ui_ScreenInfo);

    // NULL screen variables
    uic_ScreenInfo = NULL;
    ui_ScreenInfo = NULL;
    uic_ContainerInfo = NULL;
    ui_ContainerInfo = NULL;
    uic_PanelBackInfo = NULL;
    ui_PanelBackInfo = NULL;
    uic_ButtonBackInfo = NULL;
    ui_ButtonBackInfo = NULL;
    ui_topBar5 = NULL;

}
