// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENLOGO_H
#define UI_SCREENLOGO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLogo
extern void ui_ScreenLogo_screen_init(void);
extern void ui_ScreenLogo_screen_destroy(void);
extern lv_obj_t * ui_ScreenLogo;
extern lv_obj_t * ui_ContainerLogo;
extern lv_obj_t * ui_ImageLogo;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenLogo;
extern lv_obj_t * uic_ContainerLogo;
extern lv_obj_t * uic_ImageLogo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

