// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HMI_ESP32_S3_7B

#ifndef UI_SCREENINFO_H
#define UI_SCREENINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenInfo
extern void ui_ScreenInfo_screen_init(void);
extern void ui_ScreenInfo_screen_destroy(void);
extern lv_obj_t * ui_ScreenInfo;
extern lv_obj_t * ui_ContainerInfo;
extern lv_obj_t * ui_PanelBackInfo;
extern void ui_event_ButtonBackInfo(lv_event_t * e);
extern lv_obj_t * ui_ButtonBackInfo;
extern lv_obj_t * ui_topBar5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenInfo;
extern lv_obj_t * uic_ContainerInfo;
extern lv_obj_t * uic_PanelBackInfo;
extern lv_obj_t * uic_ButtonBackInfo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

